#!/usr/bin/env bash
set -euo pipefail

# Long-running local retraining script. Review settings before running.
# Set BABAPPA_RETRAIN_CLEANUP_MODE=delete and BABAPPA_RETRAIN_DELETE_INTERMEDIATES=YES
# to free disk after each completed chunk. Use quarantine or none for safer dry operation.

WORKSPACE="${BABAPPA_RETRAIN_WORKSPACE:-branch_site_v2_100k_workspace}"
PLAN_DIR="variable_length_retraining_plan"
METHODS="identity,mafft,babappalign,muscle"
FEATURE_POLICY="conservative_branch_site_normalized_v2"
DEVICE="${BABAPPA_DEVICE:-mps}"
THREADS="${BABAPPA_THREADS:-18}"
BATCH_SIZE="${BABAPPA_BATCH_SIZE:-64}"
MIN_FREE_GB="${BABAPPA_MIN_FREE_GB:-250}"
CLEANUP_MODE="${BABAPPA_RETRAIN_CLEANUP_MODE:-quarantine}"
QUARANTINE_ROOT="${BABAPPA_RETRAIN_QUARANTINE_ROOT:-${WORKSPACE}_quarantine_$(date +%Y%m%d_%H%M%S)}"
mkdir -p "$WORKSPACE" "$PLAN_DIR/stage_markers" "$PLAN_DIR/logs"
exec > >(tee -a "$PLAN_DIR/logs/variable_length_retraining_$(date +%Y%m%d_%H%M%S).log") 2>&1
echo "BABAPPA variable-length normalized-v2 retraining started"
echo "cleanup_mode=$CLEANUP_MODE workspace=$WORKSPACE device=$DEVICE threads=$THREADS"

available_gb() { df -Pk . | awk 'NR==2 {printf "%d", $4/1024/1024}'; }
require_free_space() { local free; free=$(available_gb); if [ "$free" -lt "$MIN_FREE_GB" ]; then echo "free disk ${free}GB is below required ${MIN_FREE_GB}GB" >&2; exit 3; fi; }
cleanup_path() {
  local path="$1"
  [ -e "$path" ] || return 0
  case "$CLEANUP_MODE" in
    delete)
      if [ "${BABAPPA_RETRAIN_DELETE_INTERMEDIATES:-NO}" != "YES" ]; then echo "delete cleanup requires BABAPPA_RETRAIN_DELETE_INTERMEDIATES=YES" >&2; exit 4; fi
      rm -rf "$path"
      ;;
    quarantine)
      mkdir -p "$QUARANTINE_ROOT"
      mkdir -p "$QUARANTINE_ROOT/$(dirname "$path")"
      mv "$path" "$QUARANTINE_ROOT/$path"
      ;;
    none)
      echo "keeping $path"
      ;;
    *) echo "unknown cleanup mode: $CLEANUP_MODE" >&2; exit 5 ;;
  esac
}
run_once() { local marker="$1"; shift; if [ -f "$marker" ]; then echo "skip completed $marker"; else require_free_space; "$@"; touch "$marker"; fi; }
require_alignment_methods() {
  python - "$1" "$2" <<'PY'
import json, sys
from pathlib import Path
align_dir = Path(sys.argv[1])
expected = [m.strip() for m in sys.argv[2].split(',') if m.strip()]
manifest = align_dir / 'alignment_manifest.json'
if not manifest.exists():
    raise SystemExit(f'missing alignment manifest: {manifest}')
data = json.loads(manifest.read_text())
available = set(data.get('methods') or [])
missing = [m for m in expected if m not in available]
if missing:
    warnings = data.get('warnings') or []
    raise SystemExit('alignment methods missing: ' + ','.join(missing) + '; warnings=' + ','.join(map(str, warnings)))
print('alignment methods available: ' + ','.join(expected))
PY
}

echo "=== tier low ==="
mkdir -p "$WORKSPACE/tier_low_datasets"
echo "--- chunk low_short_6taxa: families=5000 taxa=6 codons=120 ---"
run_once "$PLAN_DIR/stage_markers/.stage_complete_low_short_6taxa_simulate" babappa simulate --outdir "$WORKSPACE/sim_low_short_6taxa" --n-families 5000 --n-taxa 6 --n-codons 120 --seed 42 --positive-rate 0.5 --selected-site-fraction 0.03 --mutation-rate 0.04 --saturation-tier low --workers "$THREADS"
run_once "$PLAN_DIR/stage_markers/.stage_complete_low_short_6taxa_validate_sim" babappa validate-sim --sim-dir "$WORKSPACE/sim_low_short_6taxa" --require-branch-truth
run_once "$PLAN_DIR/stage_markers/.stage_complete_low_short_6taxa_align" babappa align-external --sim-dir "$WORKSPACE/sim_low_short_6taxa" --outdir "$WORKSPACE/align_low_short_6taxa" --methods "$METHODS" --threads "$THREADS"
run_once "$PLAN_DIR/stage_markers/.stage_complete_low_short_6taxa_align_methods" require_alignment_methods "$WORKSPACE/align_low_short_6taxa" "$METHODS"
run_once "$PLAN_DIR/stage_markers/.stage_complete_low_short_6taxa_site_map" babappa build-site-map --sim-dir "$WORKSPACE/sim_low_short_6taxa" --align-dir "$WORKSPACE/align_low_short_6taxa" --outdir "$WORKSPACE/site_map_low_short_6taxa" --methods "$METHODS" --workers "$THREADS"
run_once "$PLAN_DIR/stage_markers/.stage_complete_low_short_6taxa_method_policy" babappa aligner-method-policy --align-dir "$WORKSPACE/align_low_short_6taxa" --site-map-dir "$WORKSPACE/site_map_low_short_6taxa" --outdir "$WORKSPACE/method_policy_low_short_6taxa" --max-conflict-fraction 0.03 --max-frame-error-fraction 0.0 --max-method-failure-fraction 0.01
run_once "$PLAN_DIR/stage_markers/.stage_complete_low_short_6taxa_tensors" babappa build-tensors --sim-dir "$WORKSPACE/sim_low_short_6taxa" --align-dir "$WORKSPACE/align_low_short_6taxa" --outdir "$WORKSPACE/tensors_low_short_6taxa" --methods "$METHODS" --workers "$THREADS"
run_once "$PLAN_DIR/stage_markers/.stage_complete_low_short_6taxa_index" babappa index-dataset --tensor-dir "$WORKSPACE/tensors_low_short_6taxa" --outdir "$WORKSPACE/dataset_low_short_6taxa" --methods "$METHODS" --workers "$THREADS"
run_once "$PLAN_DIR/stage_markers/.stage_complete_low_short_6taxa_labels" babappa extract-branch-site-labels --dataset-dir "$WORKSPACE/dataset_low_short_6taxa" --site-map-dir "$WORKSPACE/site_map_low_short_6taxa" --outdir "$WORKSPACE/labels_low_short_6taxa" --truth-mode explicit --aligned-site-mode mapped --foreground-source truth --streaming-output
run_once "$PLAN_DIR/stage_markers/.stage_complete_low_short_6taxa_branch_dataset" babappa build-branch-site-dataset --dataset-dir "$WORKSPACE/dataset_low_short_6taxa" --branch-site-labels "$WORKSPACE/labels_low_short_6taxa/branch_site_oracle_labels.tsv" --outdir "$WORKSPACE/branch_dataset_low_short_6taxa" --negative-downsample-ratio 5 --seed 42 --require-mappable-sites --streaming --max-output-rows 700000
run_once "$PLAN_DIR/stage_markers/.stage_complete_low_short_6taxa_validate_branch_dataset" babappa validate-branch-site-dataset --branch-site-dataset-dir "$WORKSPACE/branch_dataset_low_short_6taxa"
cleanup_path "$WORKSPACE/sim_low_short_6taxa"; cleanup_path "$WORKSPACE/align_low_short_6taxa"; cleanup_path "$WORKSPACE/site_map_low_short_6taxa"; cleanup_path "$WORKSPACE/method_policy_low_short_6taxa"; cleanup_path "$WORKSPACE/tensors_low_short_6taxa"; cleanup_path "$WORKSPACE/dataset_low_short_6taxa"; cleanup_path "$WORKSPACE/labels_low_short_6taxa"

echo "--- chunk low_compact_8taxa: families=5000 taxa=8 codons=240 ---"
run_once "$PLAN_DIR/stage_markers/.stage_complete_low_compact_8taxa_simulate" babappa simulate --outdir "$WORKSPACE/sim_low_compact_8taxa" --n-families 5000 --n-taxa 8 --n-codons 240 --seed 43 --positive-rate 0.5 --selected-site-fraction 0.04 --mutation-rate 0.045 --saturation-tier low --workers "$THREADS"
run_once "$PLAN_DIR/stage_markers/.stage_complete_low_compact_8taxa_validate_sim" babappa validate-sim --sim-dir "$WORKSPACE/sim_low_compact_8taxa" --require-branch-truth
run_once "$PLAN_DIR/stage_markers/.stage_complete_low_compact_8taxa_align" babappa align-external --sim-dir "$WORKSPACE/sim_low_compact_8taxa" --outdir "$WORKSPACE/align_low_compact_8taxa" --methods "$METHODS" --threads "$THREADS"
run_once "$PLAN_DIR/stage_markers/.stage_complete_low_compact_8taxa_align_methods" require_alignment_methods "$WORKSPACE/align_low_compact_8taxa" "$METHODS"
run_once "$PLAN_DIR/stage_markers/.stage_complete_low_compact_8taxa_site_map" babappa build-site-map --sim-dir "$WORKSPACE/sim_low_compact_8taxa" --align-dir "$WORKSPACE/align_low_compact_8taxa" --outdir "$WORKSPACE/site_map_low_compact_8taxa" --methods "$METHODS" --workers "$THREADS"
run_once "$PLAN_DIR/stage_markers/.stage_complete_low_compact_8taxa_method_policy" babappa aligner-method-policy --align-dir "$WORKSPACE/align_low_compact_8taxa" --site-map-dir "$WORKSPACE/site_map_low_compact_8taxa" --outdir "$WORKSPACE/method_policy_low_compact_8taxa" --max-conflict-fraction 0.03 --max-frame-error-fraction 0.0 --max-method-failure-fraction 0.01
run_once "$PLAN_DIR/stage_markers/.stage_complete_low_compact_8taxa_tensors" babappa build-tensors --sim-dir "$WORKSPACE/sim_low_compact_8taxa" --align-dir "$WORKSPACE/align_low_compact_8taxa" --outdir "$WORKSPACE/tensors_low_compact_8taxa" --methods "$METHODS" --workers "$THREADS"
run_once "$PLAN_DIR/stage_markers/.stage_complete_low_compact_8taxa_index" babappa index-dataset --tensor-dir "$WORKSPACE/tensors_low_compact_8taxa" --outdir "$WORKSPACE/dataset_low_compact_8taxa" --methods "$METHODS" --workers "$THREADS"
run_once "$PLAN_DIR/stage_markers/.stage_complete_low_compact_8taxa_labels" babappa extract-branch-site-labels --dataset-dir "$WORKSPACE/dataset_low_compact_8taxa" --site-map-dir "$WORKSPACE/site_map_low_compact_8taxa" --outdir "$WORKSPACE/labels_low_compact_8taxa" --truth-mode explicit --aligned-site-mode mapped --foreground-source truth --streaming-output
run_once "$PLAN_DIR/stage_markers/.stage_complete_low_compact_8taxa_branch_dataset" babappa build-branch-site-dataset --dataset-dir "$WORKSPACE/dataset_low_compact_8taxa" --branch-site-labels "$WORKSPACE/labels_low_compact_8taxa/branch_site_oracle_labels.tsv" --outdir "$WORKSPACE/branch_dataset_low_compact_8taxa" --negative-downsample-ratio 5 --seed 42 --require-mappable-sites --streaming --max-output-rows 700000
run_once "$PLAN_DIR/stage_markers/.stage_complete_low_compact_8taxa_validate_branch_dataset" babappa validate-branch-site-dataset --branch-site-dataset-dir "$WORKSPACE/branch_dataset_low_compact_8taxa"
cleanup_path "$WORKSPACE/sim_low_compact_8taxa"; cleanup_path "$WORKSPACE/align_low_compact_8taxa"; cleanup_path "$WORKSPACE/site_map_low_compact_8taxa"; cleanup_path "$WORKSPACE/method_policy_low_compact_8taxa"; cleanup_path "$WORKSPACE/tensors_low_compact_8taxa"; cleanup_path "$WORKSPACE/dataset_low_compact_8taxa"; cleanup_path "$WORKSPACE/labels_low_compact_8taxa"

echo "--- chunk low_standard_12taxa: families=5000 taxa=12 codons=420 ---"
run_once "$PLAN_DIR/stage_markers/.stage_complete_low_standard_12taxa_simulate" babappa simulate --outdir "$WORKSPACE/sim_low_standard_12taxa" --n-families 5000 --n-taxa 12 --n-codons 420 --seed 44 --positive-rate 0.5 --selected-site-fraction 0.05 --mutation-rate 0.05 --saturation-tier low --workers "$THREADS"
run_once "$PLAN_DIR/stage_markers/.stage_complete_low_standard_12taxa_validate_sim" babappa validate-sim --sim-dir "$WORKSPACE/sim_low_standard_12taxa" --require-branch-truth
run_once "$PLAN_DIR/stage_markers/.stage_complete_low_standard_12taxa_align" babappa align-external --sim-dir "$WORKSPACE/sim_low_standard_12taxa" --outdir "$WORKSPACE/align_low_standard_12taxa" --methods "$METHODS" --threads "$THREADS"
run_once "$PLAN_DIR/stage_markers/.stage_complete_low_standard_12taxa_align_methods" require_alignment_methods "$WORKSPACE/align_low_standard_12taxa" "$METHODS"
run_once "$PLAN_DIR/stage_markers/.stage_complete_low_standard_12taxa_site_map" babappa build-site-map --sim-dir "$WORKSPACE/sim_low_standard_12taxa" --align-dir "$WORKSPACE/align_low_standard_12taxa" --outdir "$WORKSPACE/site_map_low_standard_12taxa" --methods "$METHODS" --workers "$THREADS"
run_once "$PLAN_DIR/stage_markers/.stage_complete_low_standard_12taxa_method_policy" babappa aligner-method-policy --align-dir "$WORKSPACE/align_low_standard_12taxa" --site-map-dir "$WORKSPACE/site_map_low_standard_12taxa" --outdir "$WORKSPACE/method_policy_low_standard_12taxa" --max-conflict-fraction 0.03 --max-frame-error-fraction 0.0 --max-method-failure-fraction 0.01
run_once "$PLAN_DIR/stage_markers/.stage_complete_low_standard_12taxa_tensors" babappa build-tensors --sim-dir "$WORKSPACE/sim_low_standard_12taxa" --align-dir "$WORKSPACE/align_low_standard_12taxa" --outdir "$WORKSPACE/tensors_low_standard_12taxa" --methods "$METHODS" --workers "$THREADS"
run_once "$PLAN_DIR/stage_markers/.stage_complete_low_standard_12taxa_index" babappa index-dataset --tensor-dir "$WORKSPACE/tensors_low_standard_12taxa" --outdir "$WORKSPACE/dataset_low_standard_12taxa" --methods "$METHODS" --workers "$THREADS"
run_once "$PLAN_DIR/stage_markers/.stage_complete_low_standard_12taxa_labels" babappa extract-branch-site-labels --dataset-dir "$WORKSPACE/dataset_low_standard_12taxa" --site-map-dir "$WORKSPACE/site_map_low_standard_12taxa" --outdir "$WORKSPACE/labels_low_standard_12taxa" --truth-mode explicit --aligned-site-mode mapped --foreground-source truth --streaming-output
run_once "$PLAN_DIR/stage_markers/.stage_complete_low_standard_12taxa_branch_dataset" babappa build-branch-site-dataset --dataset-dir "$WORKSPACE/dataset_low_standard_12taxa" --branch-site-labels "$WORKSPACE/labels_low_standard_12taxa/branch_site_oracle_labels.tsv" --outdir "$WORKSPACE/branch_dataset_low_standard_12taxa" --negative-downsample-ratio 5 --seed 42 --require-mappable-sites --streaming --max-output-rows 700000
run_once "$PLAN_DIR/stage_markers/.stage_complete_low_standard_12taxa_validate_branch_dataset" babappa validate-branch-site-dataset --branch-site-dataset-dir "$WORKSPACE/branch_dataset_low_standard_12taxa"
cleanup_path "$WORKSPACE/sim_low_standard_12taxa"; cleanup_path "$WORKSPACE/align_low_standard_12taxa"; cleanup_path "$WORKSPACE/site_map_low_standard_12taxa"; cleanup_path "$WORKSPACE/method_policy_low_standard_12taxa"; cleanup_path "$WORKSPACE/tensors_low_standard_12taxa"; cleanup_path "$WORKSPACE/dataset_low_standard_12taxa"; cleanup_path "$WORKSPACE/labels_low_standard_12taxa"

echo "--- chunk low_long_20taxa: families=5000 taxa=20 codons=720 ---"
run_once "$PLAN_DIR/stage_markers/.stage_complete_low_long_20taxa_simulate" babappa simulate --outdir "$WORKSPACE/sim_low_long_20taxa" --n-families 5000 --n-taxa 20 --n-codons 720 --seed 45 --positive-rate 0.5 --selected-site-fraction 0.04 --mutation-rate 0.055 --saturation-tier low --workers "$THREADS"
run_once "$PLAN_DIR/stage_markers/.stage_complete_low_long_20taxa_validate_sim" babappa validate-sim --sim-dir "$WORKSPACE/sim_low_long_20taxa" --require-branch-truth
run_once "$PLAN_DIR/stage_markers/.stage_complete_low_long_20taxa_align" babappa align-external --sim-dir "$WORKSPACE/sim_low_long_20taxa" --outdir "$WORKSPACE/align_low_long_20taxa" --methods "$METHODS" --threads "$THREADS"
run_once "$PLAN_DIR/stage_markers/.stage_complete_low_long_20taxa_align_methods" require_alignment_methods "$WORKSPACE/align_low_long_20taxa" "$METHODS"
run_once "$PLAN_DIR/stage_markers/.stage_complete_low_long_20taxa_site_map" babappa build-site-map --sim-dir "$WORKSPACE/sim_low_long_20taxa" --align-dir "$WORKSPACE/align_low_long_20taxa" --outdir "$WORKSPACE/site_map_low_long_20taxa" --methods "$METHODS" --workers "$THREADS"
run_once "$PLAN_DIR/stage_markers/.stage_complete_low_long_20taxa_method_policy" babappa aligner-method-policy --align-dir "$WORKSPACE/align_low_long_20taxa" --site-map-dir "$WORKSPACE/site_map_low_long_20taxa" --outdir "$WORKSPACE/method_policy_low_long_20taxa" --max-conflict-fraction 0.03 --max-frame-error-fraction 0.0 --max-method-failure-fraction 0.01
run_once "$PLAN_DIR/stage_markers/.stage_complete_low_long_20taxa_tensors" babappa build-tensors --sim-dir "$WORKSPACE/sim_low_long_20taxa" --align-dir "$WORKSPACE/align_low_long_20taxa" --outdir "$WORKSPACE/tensors_low_long_20taxa" --methods "$METHODS" --workers "$THREADS"
run_once "$PLAN_DIR/stage_markers/.stage_complete_low_long_20taxa_index" babappa index-dataset --tensor-dir "$WORKSPACE/tensors_low_long_20taxa" --outdir "$WORKSPACE/dataset_low_long_20taxa" --methods "$METHODS" --workers "$THREADS"
run_once "$PLAN_DIR/stage_markers/.stage_complete_low_long_20taxa_labels" babappa extract-branch-site-labels --dataset-dir "$WORKSPACE/dataset_low_long_20taxa" --site-map-dir "$WORKSPACE/site_map_low_long_20taxa" --outdir "$WORKSPACE/labels_low_long_20taxa" --truth-mode explicit --aligned-site-mode mapped --foreground-source truth --streaming-output
run_once "$PLAN_DIR/stage_markers/.stage_complete_low_long_20taxa_branch_dataset" babappa build-branch-site-dataset --dataset-dir "$WORKSPACE/dataset_low_long_20taxa" --branch-site-labels "$WORKSPACE/labels_low_long_20taxa/branch_site_oracle_labels.tsv" --outdir "$WORKSPACE/branch_dataset_low_long_20taxa" --negative-downsample-ratio 5 --seed 42 --require-mappable-sites --streaming --max-output-rows 700000
run_once "$PLAN_DIR/stage_markers/.stage_complete_low_long_20taxa_validate_branch_dataset" babappa validate-branch-site-dataset --branch-site-dataset-dir "$WORKSPACE/branch_dataset_low_long_20taxa"
cleanup_path "$WORKSPACE/sim_low_long_20taxa"; cleanup_path "$WORKSPACE/align_low_long_20taxa"; cleanup_path "$WORKSPACE/site_map_low_long_20taxa"; cleanup_path "$WORKSPACE/method_policy_low_long_20taxa"; cleanup_path "$WORKSPACE/tensors_low_long_20taxa"; cleanup_path "$WORKSPACE/dataset_low_long_20taxa"; cleanup_path "$WORKSPACE/labels_low_long_20taxa"

echo "--- chunk low_very_long_32taxa: families=5000 taxa=32 codons=960 ---"
run_once "$PLAN_DIR/stage_markers/.stage_complete_low_very_long_32taxa_simulate" babappa simulate --outdir "$WORKSPACE/sim_low_very_long_32taxa" --n-families 5000 --n-taxa 32 --n-codons 960 --seed 46 --positive-rate 0.5 --selected-site-fraction 0.03 --mutation-rate 0.06 --saturation-tier low --workers "$THREADS"
run_once "$PLAN_DIR/stage_markers/.stage_complete_low_very_long_32taxa_validate_sim" babappa validate-sim --sim-dir "$WORKSPACE/sim_low_very_long_32taxa" --require-branch-truth
run_once "$PLAN_DIR/stage_markers/.stage_complete_low_very_long_32taxa_align" babappa align-external --sim-dir "$WORKSPACE/sim_low_very_long_32taxa" --outdir "$WORKSPACE/align_low_very_long_32taxa" --methods "$METHODS" --threads "$THREADS"
run_once "$PLAN_DIR/stage_markers/.stage_complete_low_very_long_32taxa_align_methods" require_alignment_methods "$WORKSPACE/align_low_very_long_32taxa" "$METHODS"
run_once "$PLAN_DIR/stage_markers/.stage_complete_low_very_long_32taxa_site_map" babappa build-site-map --sim-dir "$WORKSPACE/sim_low_very_long_32taxa" --align-dir "$WORKSPACE/align_low_very_long_32taxa" --outdir "$WORKSPACE/site_map_low_very_long_32taxa" --methods "$METHODS" --workers "$THREADS"
run_once "$PLAN_DIR/stage_markers/.stage_complete_low_very_long_32taxa_method_policy" babappa aligner-method-policy --align-dir "$WORKSPACE/align_low_very_long_32taxa" --site-map-dir "$WORKSPACE/site_map_low_very_long_32taxa" --outdir "$WORKSPACE/method_policy_low_very_long_32taxa" --max-conflict-fraction 0.03 --max-frame-error-fraction 0.0 --max-method-failure-fraction 0.01
run_once "$PLAN_DIR/stage_markers/.stage_complete_low_very_long_32taxa_tensors" babappa build-tensors --sim-dir "$WORKSPACE/sim_low_very_long_32taxa" --align-dir "$WORKSPACE/align_low_very_long_32taxa" --outdir "$WORKSPACE/tensors_low_very_long_32taxa" --methods "$METHODS" --workers "$THREADS"
run_once "$PLAN_DIR/stage_markers/.stage_complete_low_very_long_32taxa_index" babappa index-dataset --tensor-dir "$WORKSPACE/tensors_low_very_long_32taxa" --outdir "$WORKSPACE/dataset_low_very_long_32taxa" --methods "$METHODS" --workers "$THREADS"
run_once "$PLAN_DIR/stage_markers/.stage_complete_low_very_long_32taxa_labels" babappa extract-branch-site-labels --dataset-dir "$WORKSPACE/dataset_low_very_long_32taxa" --site-map-dir "$WORKSPACE/site_map_low_very_long_32taxa" --outdir "$WORKSPACE/labels_low_very_long_32taxa" --truth-mode explicit --aligned-site-mode mapped --foreground-source truth --streaming-output
run_once "$PLAN_DIR/stage_markers/.stage_complete_low_very_long_32taxa_branch_dataset" babappa build-branch-site-dataset --dataset-dir "$WORKSPACE/dataset_low_very_long_32taxa" --branch-site-labels "$WORKSPACE/labels_low_very_long_32taxa/branch_site_oracle_labels.tsv" --outdir "$WORKSPACE/branch_dataset_low_very_long_32taxa" --negative-downsample-ratio 5 --seed 42 --require-mappable-sites --streaming --max-output-rows 700000
run_once "$PLAN_DIR/stage_markers/.stage_complete_low_very_long_32taxa_validate_branch_dataset" babappa validate-branch-site-dataset --branch-site-dataset-dir "$WORKSPACE/branch_dataset_low_very_long_32taxa"
cleanup_path "$WORKSPACE/sim_low_very_long_32taxa"; cleanup_path "$WORKSPACE/align_low_very_long_32taxa"; cleanup_path "$WORKSPACE/site_map_low_very_long_32taxa"; cleanup_path "$WORKSPACE/method_policy_low_very_long_32taxa"; cleanup_path "$WORKSPACE/tensors_low_very_long_32taxa"; cleanup_path "$WORKSPACE/dataset_low_very_long_32taxa"; cleanup_path "$WORKSPACE/labels_low_very_long_32taxa"

run_once "$PLAN_DIR/stage_markers/.stage_complete_low_merge" babappa merge-branch-site-datasets --dataset-dirs "$WORKSPACE/branch_dataset_low_short_6taxa,$WORKSPACE/branch_dataset_low_compact_8taxa,$WORKSPACE/branch_dataset_low_standard_12taxa,$WORKSPACE/branch_dataset_low_long_20taxa,$WORKSPACE/branch_dataset_low_very_long_32taxa" --outdir "$WORKSPACE/branch_site_dataset_low_merged"
run_once "$PLAN_DIR/stage_markers/.stage_complete_low_train" babappa train-branch-site-neural --branch-site-dataset-dir "$WORKSPACE/branch_site_dataset_low_merged" --outdir "$WORKSPACE/branch_site_neural_low" --device "$DEVICE" --batch-size "$BATCH_SIZE" --threads "$THREADS" --feature-policy "$FEATURE_POLICY" --epochs 10 --learning-rate 0.001 --weight-decay 0.0001 --hidden-dim 64 --dropout 0.1 --positive-class-weight auto --monitor-metric val_auroc --max-train-items 300000 --max-val-items 75000 --max-calib-items 75000 --max-test-items 75000
run_once "$PLAN_DIR/stage_markers/.stage_complete_low_validate_train" babappa validate-branch-site-neural --model-dir "$WORKSPACE/branch_site_neural_low"
run_once "$PLAN_DIR/stage_markers/.stage_complete_low_calibrate" babappa calibrate-branch-site-neural --model-dir "$WORKSPACE/branch_site_neural_low" --outdir "$WORKSPACE/branch_site_calibration_low"
run_once "$PLAN_DIR/stage_markers/.stage_complete_low_validate_calibration" babappa validate-branch-site-calibration --calibration-dir "$WORKSPACE/branch_site_calibration_low"
run_once "$PLAN_DIR/stage_markers/.stage_complete_low_aggregate" babappa aggregate-branch-sites --predictions "$WORKSPACE/branch_site_neural_low/branch_site_neural_predictions.tsv" --outdir "$WORKSPACE/branch_aggregation_low"
run_once "$PLAN_DIR/stage_markers/.stage_complete_low_controls" babappa branch-aggregation-controls --predictions "$WORKSPACE/branch_site_neural_low/branch_site_neural_predictions.tsv" --outdir "$WORKSPACE/branch_aggregation_controls_low" --n-permutations 100 --seed 42 --workers "$THREADS"
run_once "$PLAN_DIR/stage_markers/.stage_complete_low_threshold" babappa branch-site-threshold-policy --predictions "$WORKSPACE/branch_site_calibration_low/branch_site_calibrated_predictions.tsv" --outdir "$WORKSPACE/branch_site_threshold_policy_low" --probability-column prob_positive_raw --calibrated-probability-column prob_positive_calibrated
run_once "$PLAN_DIR/stage_markers/.stage_complete_low_aggregation_policy" babappa branch-aggregation-threshold-policy --aggregation-dir "$WORKSPACE/branch_aggregation_low" --outdir "$WORKSPACE/branch_aggregation_threshold_policy_low"
run_once "$PLAN_DIR/stage_markers/.stage_complete_low_summary" babappa summarize-branch-site-run --outdir "$WORKSPACE/branch_site_run_summary_low" --title "BABAPPA variable-length normalized-v2 low summary" --branch-site-dataset-dir "$WORKSPACE/branch_site_dataset_low_merged" --branch-site-neural-dir "$WORKSPACE/branch_site_neural_low" --branch-site-calibration-dir "$WORKSPACE/branch_site_calibration_low" --branch-aggregation-dir "$WORKSPACE/branch_aggregation_low" --branch-aggregation-controls-dir "$WORKSPACE/branch_aggregation_controls_low" --branch-site-threshold-policy-dir "$WORKSPACE/branch_site_threshold_policy_low" --branch-aggregation-threshold-policy-dir "$WORKSPACE/branch_aggregation_threshold_policy_low"
cleanup_path "$WORKSPACE/branch_site_dataset_low_merged"; for d in "$WORKSPACE/branch_dataset_low_short_6taxa" "$WORKSPACE/branch_dataset_low_compact_8taxa" "$WORKSPACE/branch_dataset_low_standard_12taxa" "$WORKSPACE/branch_dataset_low_long_20taxa" "$WORKSPACE/branch_dataset_low_very_long_32taxa"; do cleanup_path "$d"; done

echo "=== tier moderate ==="
mkdir -p "$WORKSPACE/tier_moderate_datasets"
echo "--- chunk moderate_short_6taxa: families=5000 taxa=6 codons=120 ---"
run_once "$PLAN_DIR/stage_markers/.stage_complete_moderate_short_6taxa_simulate" babappa simulate --outdir "$WORKSPACE/sim_moderate_short_6taxa" --n-families 5000 --n-taxa 6 --n-codons 120 --seed 1042 --positive-rate 0.5 --selected-site-fraction 0.03 --mutation-rate 0.04 --saturation-tier moderate --workers "$THREADS"
run_once "$PLAN_DIR/stage_markers/.stage_complete_moderate_short_6taxa_validate_sim" babappa validate-sim --sim-dir "$WORKSPACE/sim_moderate_short_6taxa" --require-branch-truth
run_once "$PLAN_DIR/stage_markers/.stage_complete_moderate_short_6taxa_align" babappa align-external --sim-dir "$WORKSPACE/sim_moderate_short_6taxa" --outdir "$WORKSPACE/align_moderate_short_6taxa" --methods "$METHODS" --threads "$THREADS"
run_once "$PLAN_DIR/stage_markers/.stage_complete_moderate_short_6taxa_align_methods" require_alignment_methods "$WORKSPACE/align_moderate_short_6taxa" "$METHODS"
run_once "$PLAN_DIR/stage_markers/.stage_complete_moderate_short_6taxa_site_map" babappa build-site-map --sim-dir "$WORKSPACE/sim_moderate_short_6taxa" --align-dir "$WORKSPACE/align_moderate_short_6taxa" --outdir "$WORKSPACE/site_map_moderate_short_6taxa" --methods "$METHODS" --workers "$THREADS"
run_once "$PLAN_DIR/stage_markers/.stage_complete_moderate_short_6taxa_method_policy" babappa aligner-method-policy --align-dir "$WORKSPACE/align_moderate_short_6taxa" --site-map-dir "$WORKSPACE/site_map_moderate_short_6taxa" --outdir "$WORKSPACE/method_policy_moderate_short_6taxa" --max-conflict-fraction 0.03 --max-frame-error-fraction 0.0 --max-method-failure-fraction 0.01
run_once "$PLAN_DIR/stage_markers/.stage_complete_moderate_short_6taxa_tensors" babappa build-tensors --sim-dir "$WORKSPACE/sim_moderate_short_6taxa" --align-dir "$WORKSPACE/align_moderate_short_6taxa" --outdir "$WORKSPACE/tensors_moderate_short_6taxa" --methods "$METHODS" --workers "$THREADS"
run_once "$PLAN_DIR/stage_markers/.stage_complete_moderate_short_6taxa_index" babappa index-dataset --tensor-dir "$WORKSPACE/tensors_moderate_short_6taxa" --outdir "$WORKSPACE/dataset_moderate_short_6taxa" --methods "$METHODS" --workers "$THREADS"
run_once "$PLAN_DIR/stage_markers/.stage_complete_moderate_short_6taxa_labels" babappa extract-branch-site-labels --dataset-dir "$WORKSPACE/dataset_moderate_short_6taxa" --site-map-dir "$WORKSPACE/site_map_moderate_short_6taxa" --outdir "$WORKSPACE/labels_moderate_short_6taxa" --truth-mode explicit --aligned-site-mode mapped --foreground-source truth --streaming-output
run_once "$PLAN_DIR/stage_markers/.stage_complete_moderate_short_6taxa_branch_dataset" babappa build-branch-site-dataset --dataset-dir "$WORKSPACE/dataset_moderate_short_6taxa" --branch-site-labels "$WORKSPACE/labels_moderate_short_6taxa/branch_site_oracle_labels.tsv" --outdir "$WORKSPACE/branch_dataset_moderate_short_6taxa" --negative-downsample-ratio 5 --seed 42 --require-mappable-sites --streaming --max-output-rows 700000
run_once "$PLAN_DIR/stage_markers/.stage_complete_moderate_short_6taxa_validate_branch_dataset" babappa validate-branch-site-dataset --branch-site-dataset-dir "$WORKSPACE/branch_dataset_moderate_short_6taxa"
cleanup_path "$WORKSPACE/sim_moderate_short_6taxa"; cleanup_path "$WORKSPACE/align_moderate_short_6taxa"; cleanup_path "$WORKSPACE/site_map_moderate_short_6taxa"; cleanup_path "$WORKSPACE/method_policy_moderate_short_6taxa"; cleanup_path "$WORKSPACE/tensors_moderate_short_6taxa"; cleanup_path "$WORKSPACE/dataset_moderate_short_6taxa"; cleanup_path "$WORKSPACE/labels_moderate_short_6taxa"

echo "--- chunk moderate_compact_8taxa: families=5000 taxa=8 codons=240 ---"
run_once "$PLAN_DIR/stage_markers/.stage_complete_moderate_compact_8taxa_simulate" babappa simulate --outdir "$WORKSPACE/sim_moderate_compact_8taxa" --n-families 5000 --n-taxa 8 --n-codons 240 --seed 1043 --positive-rate 0.5 --selected-site-fraction 0.04 --mutation-rate 0.045 --saturation-tier moderate --workers "$THREADS"
run_once "$PLAN_DIR/stage_markers/.stage_complete_moderate_compact_8taxa_validate_sim" babappa validate-sim --sim-dir "$WORKSPACE/sim_moderate_compact_8taxa" --require-branch-truth
run_once "$PLAN_DIR/stage_markers/.stage_complete_moderate_compact_8taxa_align" babappa align-external --sim-dir "$WORKSPACE/sim_moderate_compact_8taxa" --outdir "$WORKSPACE/align_moderate_compact_8taxa" --methods "$METHODS" --threads "$THREADS"
run_once "$PLAN_DIR/stage_markers/.stage_complete_moderate_compact_8taxa_align_methods" require_alignment_methods "$WORKSPACE/align_moderate_compact_8taxa" "$METHODS"
run_once "$PLAN_DIR/stage_markers/.stage_complete_moderate_compact_8taxa_site_map" babappa build-site-map --sim-dir "$WORKSPACE/sim_moderate_compact_8taxa" --align-dir "$WORKSPACE/align_moderate_compact_8taxa" --outdir "$WORKSPACE/site_map_moderate_compact_8taxa" --methods "$METHODS" --workers "$THREADS"
run_once "$PLAN_DIR/stage_markers/.stage_complete_moderate_compact_8taxa_method_policy" babappa aligner-method-policy --align-dir "$WORKSPACE/align_moderate_compact_8taxa" --site-map-dir "$WORKSPACE/site_map_moderate_compact_8taxa" --outdir "$WORKSPACE/method_policy_moderate_compact_8taxa" --max-conflict-fraction 0.03 --max-frame-error-fraction 0.0 --max-method-failure-fraction 0.01
run_once "$PLAN_DIR/stage_markers/.stage_complete_moderate_compact_8taxa_tensors" babappa build-tensors --sim-dir "$WORKSPACE/sim_moderate_compact_8taxa" --align-dir "$WORKSPACE/align_moderate_compact_8taxa" --outdir "$WORKSPACE/tensors_moderate_compact_8taxa" --methods "$METHODS" --workers "$THREADS"
run_once "$PLAN_DIR/stage_markers/.stage_complete_moderate_compact_8taxa_index" babappa index-dataset --tensor-dir "$WORKSPACE/tensors_moderate_compact_8taxa" --outdir "$WORKSPACE/dataset_moderate_compact_8taxa" --methods "$METHODS" --workers "$THREADS"
run_once "$PLAN_DIR/stage_markers/.stage_complete_moderate_compact_8taxa_labels" babappa extract-branch-site-labels --dataset-dir "$WORKSPACE/dataset_moderate_compact_8taxa" --site-map-dir "$WORKSPACE/site_map_moderate_compact_8taxa" --outdir "$WORKSPACE/labels_moderate_compact_8taxa" --truth-mode explicit --aligned-site-mode mapped --foreground-source truth --streaming-output
run_once "$PLAN_DIR/stage_markers/.stage_complete_moderate_compact_8taxa_branch_dataset" babappa build-branch-site-dataset --dataset-dir "$WORKSPACE/dataset_moderate_compact_8taxa" --branch-site-labels "$WORKSPACE/labels_moderate_compact_8taxa/branch_site_oracle_labels.tsv" --outdir "$WORKSPACE/branch_dataset_moderate_compact_8taxa" --negative-downsample-ratio 5 --seed 42 --require-mappable-sites --streaming --max-output-rows 700000
run_once "$PLAN_DIR/stage_markers/.stage_complete_moderate_compact_8taxa_validate_branch_dataset" babappa validate-branch-site-dataset --branch-site-dataset-dir "$WORKSPACE/branch_dataset_moderate_compact_8taxa"
cleanup_path "$WORKSPACE/sim_moderate_compact_8taxa"; cleanup_path "$WORKSPACE/align_moderate_compact_8taxa"; cleanup_path "$WORKSPACE/site_map_moderate_compact_8taxa"; cleanup_path "$WORKSPACE/method_policy_moderate_compact_8taxa"; cleanup_path "$WORKSPACE/tensors_moderate_compact_8taxa"; cleanup_path "$WORKSPACE/dataset_moderate_compact_8taxa"; cleanup_path "$WORKSPACE/labels_moderate_compact_8taxa"

echo "--- chunk moderate_standard_12taxa: families=5000 taxa=12 codons=420 ---"
run_once "$PLAN_DIR/stage_markers/.stage_complete_moderate_standard_12taxa_simulate" babappa simulate --outdir "$WORKSPACE/sim_moderate_standard_12taxa" --n-families 5000 --n-taxa 12 --n-codons 420 --seed 1044 --positive-rate 0.5 --selected-site-fraction 0.05 --mutation-rate 0.05 --saturation-tier moderate --workers "$THREADS"
run_once "$PLAN_DIR/stage_markers/.stage_complete_moderate_standard_12taxa_validate_sim" babappa validate-sim --sim-dir "$WORKSPACE/sim_moderate_standard_12taxa" --require-branch-truth
run_once "$PLAN_DIR/stage_markers/.stage_complete_moderate_standard_12taxa_align" babappa align-external --sim-dir "$WORKSPACE/sim_moderate_standard_12taxa" --outdir "$WORKSPACE/align_moderate_standard_12taxa" --methods "$METHODS" --threads "$THREADS"
run_once "$PLAN_DIR/stage_markers/.stage_complete_moderate_standard_12taxa_align_methods" require_alignment_methods "$WORKSPACE/align_moderate_standard_12taxa" "$METHODS"
run_once "$PLAN_DIR/stage_markers/.stage_complete_moderate_standard_12taxa_site_map" babappa build-site-map --sim-dir "$WORKSPACE/sim_moderate_standard_12taxa" --align-dir "$WORKSPACE/align_moderate_standard_12taxa" --outdir "$WORKSPACE/site_map_moderate_standard_12taxa" --methods "$METHODS" --workers "$THREADS"
run_once "$PLAN_DIR/stage_markers/.stage_complete_moderate_standard_12taxa_method_policy" babappa aligner-method-policy --align-dir "$WORKSPACE/align_moderate_standard_12taxa" --site-map-dir "$WORKSPACE/site_map_moderate_standard_12taxa" --outdir "$WORKSPACE/method_policy_moderate_standard_12taxa" --max-conflict-fraction 0.03 --max-frame-error-fraction 0.0 --max-method-failure-fraction 0.01
run_once "$PLAN_DIR/stage_markers/.stage_complete_moderate_standard_12taxa_tensors" babappa build-tensors --sim-dir "$WORKSPACE/sim_moderate_standard_12taxa" --align-dir "$WORKSPACE/align_moderate_standard_12taxa" --outdir "$WORKSPACE/tensors_moderate_standard_12taxa" --methods "$METHODS" --workers "$THREADS"
run_once "$PLAN_DIR/stage_markers/.stage_complete_moderate_standard_12taxa_index" babappa index-dataset --tensor-dir "$WORKSPACE/tensors_moderate_standard_12taxa" --outdir "$WORKSPACE/dataset_moderate_standard_12taxa" --methods "$METHODS" --workers "$THREADS"
run_once "$PLAN_DIR/stage_markers/.stage_complete_moderate_standard_12taxa_labels" babappa extract-branch-site-labels --dataset-dir "$WORKSPACE/dataset_moderate_standard_12taxa" --site-map-dir "$WORKSPACE/site_map_moderate_standard_12taxa" --outdir "$WORKSPACE/labels_moderate_standard_12taxa" --truth-mode explicit --aligned-site-mode mapped --foreground-source truth --streaming-output
run_once "$PLAN_DIR/stage_markers/.stage_complete_moderate_standard_12taxa_branch_dataset" babappa build-branch-site-dataset --dataset-dir "$WORKSPACE/dataset_moderate_standard_12taxa" --branch-site-labels "$WORKSPACE/labels_moderate_standard_12taxa/branch_site_oracle_labels.tsv" --outdir "$WORKSPACE/branch_dataset_moderate_standard_12taxa" --negative-downsample-ratio 5 --seed 42 --require-mappable-sites --streaming --max-output-rows 700000
run_once "$PLAN_DIR/stage_markers/.stage_complete_moderate_standard_12taxa_validate_branch_dataset" babappa validate-branch-site-dataset --branch-site-dataset-dir "$WORKSPACE/branch_dataset_moderate_standard_12taxa"
cleanup_path "$WORKSPACE/sim_moderate_standard_12taxa"; cleanup_path "$WORKSPACE/align_moderate_standard_12taxa"; cleanup_path "$WORKSPACE/site_map_moderate_standard_12taxa"; cleanup_path "$WORKSPACE/method_policy_moderate_standard_12taxa"; cleanup_path "$WORKSPACE/tensors_moderate_standard_12taxa"; cleanup_path "$WORKSPACE/dataset_moderate_standard_12taxa"; cleanup_path "$WORKSPACE/labels_moderate_standard_12taxa"

echo "--- chunk moderate_long_20taxa: families=5000 taxa=20 codons=720 ---"
run_once "$PLAN_DIR/stage_markers/.stage_complete_moderate_long_20taxa_simulate" babappa simulate --outdir "$WORKSPACE/sim_moderate_long_20taxa" --n-families 5000 --n-taxa 20 --n-codons 720 --seed 1045 --positive-rate 0.5 --selected-site-fraction 0.04 --mutation-rate 0.055 --saturation-tier moderate --workers "$THREADS"
run_once "$PLAN_DIR/stage_markers/.stage_complete_moderate_long_20taxa_validate_sim" babappa validate-sim --sim-dir "$WORKSPACE/sim_moderate_long_20taxa" --require-branch-truth
run_once "$PLAN_DIR/stage_markers/.stage_complete_moderate_long_20taxa_align" babappa align-external --sim-dir "$WORKSPACE/sim_moderate_long_20taxa" --outdir "$WORKSPACE/align_moderate_long_20taxa" --methods "$METHODS" --threads "$THREADS"
run_once "$PLAN_DIR/stage_markers/.stage_complete_moderate_long_20taxa_align_methods" require_alignment_methods "$WORKSPACE/align_moderate_long_20taxa" "$METHODS"
run_once "$PLAN_DIR/stage_markers/.stage_complete_moderate_long_20taxa_site_map" babappa build-site-map --sim-dir "$WORKSPACE/sim_moderate_long_20taxa" --align-dir "$WORKSPACE/align_moderate_long_20taxa" --outdir "$WORKSPACE/site_map_moderate_long_20taxa" --methods "$METHODS" --workers "$THREADS"
run_once "$PLAN_DIR/stage_markers/.stage_complete_moderate_long_20taxa_method_policy" babappa aligner-method-policy --align-dir "$WORKSPACE/align_moderate_long_20taxa" --site-map-dir "$WORKSPACE/site_map_moderate_long_20taxa" --outdir "$WORKSPACE/method_policy_moderate_long_20taxa" --max-conflict-fraction 0.03 --max-frame-error-fraction 0.0 --max-method-failure-fraction 0.01
run_once "$PLAN_DIR/stage_markers/.stage_complete_moderate_long_20taxa_tensors" babappa build-tensors --sim-dir "$WORKSPACE/sim_moderate_long_20taxa" --align-dir "$WORKSPACE/align_moderate_long_20taxa" --outdir "$WORKSPACE/tensors_moderate_long_20taxa" --methods "$METHODS" --workers "$THREADS"
run_once "$PLAN_DIR/stage_markers/.stage_complete_moderate_long_20taxa_index" babappa index-dataset --tensor-dir "$WORKSPACE/tensors_moderate_long_20taxa" --outdir "$WORKSPACE/dataset_moderate_long_20taxa" --methods "$METHODS" --workers "$THREADS"
run_once "$PLAN_DIR/stage_markers/.stage_complete_moderate_long_20taxa_labels" babappa extract-branch-site-labels --dataset-dir "$WORKSPACE/dataset_moderate_long_20taxa" --site-map-dir "$WORKSPACE/site_map_moderate_long_20taxa" --outdir "$WORKSPACE/labels_moderate_long_20taxa" --truth-mode explicit --aligned-site-mode mapped --foreground-source truth --streaming-output
run_once "$PLAN_DIR/stage_markers/.stage_complete_moderate_long_20taxa_branch_dataset" babappa build-branch-site-dataset --dataset-dir "$WORKSPACE/dataset_moderate_long_20taxa" --branch-site-labels "$WORKSPACE/labels_moderate_long_20taxa/branch_site_oracle_labels.tsv" --outdir "$WORKSPACE/branch_dataset_moderate_long_20taxa" --negative-downsample-ratio 5 --seed 42 --require-mappable-sites --streaming --max-output-rows 700000
run_once "$PLAN_DIR/stage_markers/.stage_complete_moderate_long_20taxa_validate_branch_dataset" babappa validate-branch-site-dataset --branch-site-dataset-dir "$WORKSPACE/branch_dataset_moderate_long_20taxa"
cleanup_path "$WORKSPACE/sim_moderate_long_20taxa"; cleanup_path "$WORKSPACE/align_moderate_long_20taxa"; cleanup_path "$WORKSPACE/site_map_moderate_long_20taxa"; cleanup_path "$WORKSPACE/method_policy_moderate_long_20taxa"; cleanup_path "$WORKSPACE/tensors_moderate_long_20taxa"; cleanup_path "$WORKSPACE/dataset_moderate_long_20taxa"; cleanup_path "$WORKSPACE/labels_moderate_long_20taxa"

echo "--- chunk moderate_very_long_32taxa: families=5000 taxa=32 codons=960 ---"
run_once "$PLAN_DIR/stage_markers/.stage_complete_moderate_very_long_32taxa_simulate" babappa simulate --outdir "$WORKSPACE/sim_moderate_very_long_32taxa" --n-families 5000 --n-taxa 32 --n-codons 960 --seed 1046 --positive-rate 0.5 --selected-site-fraction 0.03 --mutation-rate 0.06 --saturation-tier moderate --workers "$THREADS"
run_once "$PLAN_DIR/stage_markers/.stage_complete_moderate_very_long_32taxa_validate_sim" babappa validate-sim --sim-dir "$WORKSPACE/sim_moderate_very_long_32taxa" --require-branch-truth
run_once "$PLAN_DIR/stage_markers/.stage_complete_moderate_very_long_32taxa_align" babappa align-external --sim-dir "$WORKSPACE/sim_moderate_very_long_32taxa" --outdir "$WORKSPACE/align_moderate_very_long_32taxa" --methods "$METHODS" --threads "$THREADS"
run_once "$PLAN_DIR/stage_markers/.stage_complete_moderate_very_long_32taxa_align_methods" require_alignment_methods "$WORKSPACE/align_moderate_very_long_32taxa" "$METHODS"
run_once "$PLAN_DIR/stage_markers/.stage_complete_moderate_very_long_32taxa_site_map" babappa build-site-map --sim-dir "$WORKSPACE/sim_moderate_very_long_32taxa" --align-dir "$WORKSPACE/align_moderate_very_long_32taxa" --outdir "$WORKSPACE/site_map_moderate_very_long_32taxa" --methods "$METHODS" --workers "$THREADS"
run_once "$PLAN_DIR/stage_markers/.stage_complete_moderate_very_long_32taxa_method_policy" babappa aligner-method-policy --align-dir "$WORKSPACE/align_moderate_very_long_32taxa" --site-map-dir "$WORKSPACE/site_map_moderate_very_long_32taxa" --outdir "$WORKSPACE/method_policy_moderate_very_long_32taxa" --max-conflict-fraction 0.03 --max-frame-error-fraction 0.0 --max-method-failure-fraction 0.01
run_once "$PLAN_DIR/stage_markers/.stage_complete_moderate_very_long_32taxa_tensors" babappa build-tensors --sim-dir "$WORKSPACE/sim_moderate_very_long_32taxa" --align-dir "$WORKSPACE/align_moderate_very_long_32taxa" --outdir "$WORKSPACE/tensors_moderate_very_long_32taxa" --methods "$METHODS" --workers "$THREADS"
run_once "$PLAN_DIR/stage_markers/.stage_complete_moderate_very_long_32taxa_index" babappa index-dataset --tensor-dir "$WORKSPACE/tensors_moderate_very_long_32taxa" --outdir "$WORKSPACE/dataset_moderate_very_long_32taxa" --methods "$METHODS" --workers "$THREADS"
run_once "$PLAN_DIR/stage_markers/.stage_complete_moderate_very_long_32taxa_labels" babappa extract-branch-site-labels --dataset-dir "$WORKSPACE/dataset_moderate_very_long_32taxa" --site-map-dir "$WORKSPACE/site_map_moderate_very_long_32taxa" --outdir "$WORKSPACE/labels_moderate_very_long_32taxa" --truth-mode explicit --aligned-site-mode mapped --foreground-source truth --streaming-output
run_once "$PLAN_DIR/stage_markers/.stage_complete_moderate_very_long_32taxa_branch_dataset" babappa build-branch-site-dataset --dataset-dir "$WORKSPACE/dataset_moderate_very_long_32taxa" --branch-site-labels "$WORKSPACE/labels_moderate_very_long_32taxa/branch_site_oracle_labels.tsv" --outdir "$WORKSPACE/branch_dataset_moderate_very_long_32taxa" --negative-downsample-ratio 5 --seed 42 --require-mappable-sites --streaming --max-output-rows 700000
run_once "$PLAN_DIR/stage_markers/.stage_complete_moderate_very_long_32taxa_validate_branch_dataset" babappa validate-branch-site-dataset --branch-site-dataset-dir "$WORKSPACE/branch_dataset_moderate_very_long_32taxa"
cleanup_path "$WORKSPACE/sim_moderate_very_long_32taxa"; cleanup_path "$WORKSPACE/align_moderate_very_long_32taxa"; cleanup_path "$WORKSPACE/site_map_moderate_very_long_32taxa"; cleanup_path "$WORKSPACE/method_policy_moderate_very_long_32taxa"; cleanup_path "$WORKSPACE/tensors_moderate_very_long_32taxa"; cleanup_path "$WORKSPACE/dataset_moderate_very_long_32taxa"; cleanup_path "$WORKSPACE/labels_moderate_very_long_32taxa"

run_once "$PLAN_DIR/stage_markers/.stage_complete_moderate_merge" babappa merge-branch-site-datasets --dataset-dirs "$WORKSPACE/branch_dataset_moderate_short_6taxa,$WORKSPACE/branch_dataset_moderate_compact_8taxa,$WORKSPACE/branch_dataset_moderate_standard_12taxa,$WORKSPACE/branch_dataset_moderate_long_20taxa,$WORKSPACE/branch_dataset_moderate_very_long_32taxa" --outdir "$WORKSPACE/branch_site_dataset_moderate_merged"
run_once "$PLAN_DIR/stage_markers/.stage_complete_moderate_train" babappa train-branch-site-neural --branch-site-dataset-dir "$WORKSPACE/branch_site_dataset_moderate_merged" --outdir "$WORKSPACE/branch_site_neural_moderate" --device "$DEVICE" --batch-size "$BATCH_SIZE" --threads "$THREADS" --feature-policy "$FEATURE_POLICY" --epochs 10 --learning-rate 0.001 --weight-decay 0.0001 --hidden-dim 64 --dropout 0.1 --positive-class-weight auto --monitor-metric val_auroc --max-train-items 300000 --max-val-items 75000 --max-calib-items 75000 --max-test-items 75000
run_once "$PLAN_DIR/stage_markers/.stage_complete_moderate_validate_train" babappa validate-branch-site-neural --model-dir "$WORKSPACE/branch_site_neural_moderate"
run_once "$PLAN_DIR/stage_markers/.stage_complete_moderate_calibrate" babappa calibrate-branch-site-neural --model-dir "$WORKSPACE/branch_site_neural_moderate" --outdir "$WORKSPACE/branch_site_calibration_moderate"
run_once "$PLAN_DIR/stage_markers/.stage_complete_moderate_validate_calibration" babappa validate-branch-site-calibration --calibration-dir "$WORKSPACE/branch_site_calibration_moderate"
run_once "$PLAN_DIR/stage_markers/.stage_complete_moderate_aggregate" babappa aggregate-branch-sites --predictions "$WORKSPACE/branch_site_neural_moderate/branch_site_neural_predictions.tsv" --outdir "$WORKSPACE/branch_aggregation_moderate"
run_once "$PLAN_DIR/stage_markers/.stage_complete_moderate_controls" babappa branch-aggregation-controls --predictions "$WORKSPACE/branch_site_neural_moderate/branch_site_neural_predictions.tsv" --outdir "$WORKSPACE/branch_aggregation_controls_moderate" --n-permutations 100 --seed 42 --workers "$THREADS"
run_once "$PLAN_DIR/stage_markers/.stage_complete_moderate_threshold" babappa branch-site-threshold-policy --predictions "$WORKSPACE/branch_site_calibration_moderate/branch_site_calibrated_predictions.tsv" --outdir "$WORKSPACE/branch_site_threshold_policy_moderate" --probability-column prob_positive_raw --calibrated-probability-column prob_positive_calibrated
run_once "$PLAN_DIR/stage_markers/.stage_complete_moderate_aggregation_policy" babappa branch-aggregation-threshold-policy --aggregation-dir "$WORKSPACE/branch_aggregation_moderate" --outdir "$WORKSPACE/branch_aggregation_threshold_policy_moderate"
run_once "$PLAN_DIR/stage_markers/.stage_complete_moderate_summary" babappa summarize-branch-site-run --outdir "$WORKSPACE/branch_site_run_summary_moderate" --title "BABAPPA variable-length normalized-v2 moderate summary" --branch-site-dataset-dir "$WORKSPACE/branch_site_dataset_moderate_merged" --branch-site-neural-dir "$WORKSPACE/branch_site_neural_moderate" --branch-site-calibration-dir "$WORKSPACE/branch_site_calibration_moderate" --branch-aggregation-dir "$WORKSPACE/branch_aggregation_moderate" --branch-aggregation-controls-dir "$WORKSPACE/branch_aggregation_controls_moderate" --branch-site-threshold-policy-dir "$WORKSPACE/branch_site_threshold_policy_moderate" --branch-aggregation-threshold-policy-dir "$WORKSPACE/branch_aggregation_threshold_policy_moderate"
cleanup_path "$WORKSPACE/branch_site_dataset_moderate_merged"; for d in "$WORKSPACE/branch_dataset_moderate_short_6taxa" "$WORKSPACE/branch_dataset_moderate_compact_8taxa" "$WORKSPACE/branch_dataset_moderate_standard_12taxa" "$WORKSPACE/branch_dataset_moderate_long_20taxa" "$WORKSPACE/branch_dataset_moderate_very_long_32taxa"; do cleanup_path "$d"; done

echo "=== tier high ==="
mkdir -p "$WORKSPACE/tier_high_datasets"
echo "--- chunk high_short_6taxa: families=5000 taxa=6 codons=120 ---"
run_once "$PLAN_DIR/stage_markers/.stage_complete_high_short_6taxa_simulate" babappa simulate --outdir "$WORKSPACE/sim_high_short_6taxa" --n-families 5000 --n-taxa 6 --n-codons 120 --seed 2042 --positive-rate 0.5 --selected-site-fraction 0.03 --mutation-rate 0.04 --saturation-tier high --workers "$THREADS"
run_once "$PLAN_DIR/stage_markers/.stage_complete_high_short_6taxa_validate_sim" babappa validate-sim --sim-dir "$WORKSPACE/sim_high_short_6taxa" --require-branch-truth
run_once "$PLAN_DIR/stage_markers/.stage_complete_high_short_6taxa_align" babappa align-external --sim-dir "$WORKSPACE/sim_high_short_6taxa" --outdir "$WORKSPACE/align_high_short_6taxa" --methods "$METHODS" --threads "$THREADS"
run_once "$PLAN_DIR/stage_markers/.stage_complete_high_short_6taxa_align_methods" require_alignment_methods "$WORKSPACE/align_high_short_6taxa" "$METHODS"
run_once "$PLAN_DIR/stage_markers/.stage_complete_high_short_6taxa_site_map" babappa build-site-map --sim-dir "$WORKSPACE/sim_high_short_6taxa" --align-dir "$WORKSPACE/align_high_short_6taxa" --outdir "$WORKSPACE/site_map_high_short_6taxa" --methods "$METHODS" --workers "$THREADS"
run_once "$PLAN_DIR/stage_markers/.stage_complete_high_short_6taxa_method_policy" babappa aligner-method-policy --align-dir "$WORKSPACE/align_high_short_6taxa" --site-map-dir "$WORKSPACE/site_map_high_short_6taxa" --outdir "$WORKSPACE/method_policy_high_short_6taxa" --max-conflict-fraction 0.03 --max-frame-error-fraction 0.0 --max-method-failure-fraction 0.01
run_once "$PLAN_DIR/stage_markers/.stage_complete_high_short_6taxa_tensors" babappa build-tensors --sim-dir "$WORKSPACE/sim_high_short_6taxa" --align-dir "$WORKSPACE/align_high_short_6taxa" --outdir "$WORKSPACE/tensors_high_short_6taxa" --methods "$METHODS" --workers "$THREADS"
run_once "$PLAN_DIR/stage_markers/.stage_complete_high_short_6taxa_index" babappa index-dataset --tensor-dir "$WORKSPACE/tensors_high_short_6taxa" --outdir "$WORKSPACE/dataset_high_short_6taxa" --methods "$METHODS" --workers "$THREADS"
run_once "$PLAN_DIR/stage_markers/.stage_complete_high_short_6taxa_labels" babappa extract-branch-site-labels --dataset-dir "$WORKSPACE/dataset_high_short_6taxa" --site-map-dir "$WORKSPACE/site_map_high_short_6taxa" --outdir "$WORKSPACE/labels_high_short_6taxa" --truth-mode explicit --aligned-site-mode mapped --foreground-source truth --streaming-output
run_once "$PLAN_DIR/stage_markers/.stage_complete_high_short_6taxa_branch_dataset" babappa build-branch-site-dataset --dataset-dir "$WORKSPACE/dataset_high_short_6taxa" --branch-site-labels "$WORKSPACE/labels_high_short_6taxa/branch_site_oracle_labels.tsv" --outdir "$WORKSPACE/branch_dataset_high_short_6taxa" --negative-downsample-ratio 5 --seed 42 --require-mappable-sites --streaming --max-output-rows 700000
run_once "$PLAN_DIR/stage_markers/.stage_complete_high_short_6taxa_validate_branch_dataset" babappa validate-branch-site-dataset --branch-site-dataset-dir "$WORKSPACE/branch_dataset_high_short_6taxa"
cleanup_path "$WORKSPACE/sim_high_short_6taxa"; cleanup_path "$WORKSPACE/align_high_short_6taxa"; cleanup_path "$WORKSPACE/site_map_high_short_6taxa"; cleanup_path "$WORKSPACE/method_policy_high_short_6taxa"; cleanup_path "$WORKSPACE/tensors_high_short_6taxa"; cleanup_path "$WORKSPACE/dataset_high_short_6taxa"; cleanup_path "$WORKSPACE/labels_high_short_6taxa"

echo "--- chunk high_compact_8taxa: families=5000 taxa=8 codons=240 ---"
run_once "$PLAN_DIR/stage_markers/.stage_complete_high_compact_8taxa_simulate" babappa simulate --outdir "$WORKSPACE/sim_high_compact_8taxa" --n-families 5000 --n-taxa 8 --n-codons 240 --seed 2043 --positive-rate 0.5 --selected-site-fraction 0.04 --mutation-rate 0.045 --saturation-tier high --workers "$THREADS"
run_once "$PLAN_DIR/stage_markers/.stage_complete_high_compact_8taxa_validate_sim" babappa validate-sim --sim-dir "$WORKSPACE/sim_high_compact_8taxa" --require-branch-truth
run_once "$PLAN_DIR/stage_markers/.stage_complete_high_compact_8taxa_align" babappa align-external --sim-dir "$WORKSPACE/sim_high_compact_8taxa" --outdir "$WORKSPACE/align_high_compact_8taxa" --methods "$METHODS" --threads "$THREADS"
run_once "$PLAN_DIR/stage_markers/.stage_complete_high_compact_8taxa_align_methods" require_alignment_methods "$WORKSPACE/align_high_compact_8taxa" "$METHODS"
run_once "$PLAN_DIR/stage_markers/.stage_complete_high_compact_8taxa_site_map" babappa build-site-map --sim-dir "$WORKSPACE/sim_high_compact_8taxa" --align-dir "$WORKSPACE/align_high_compact_8taxa" --outdir "$WORKSPACE/site_map_high_compact_8taxa" --methods "$METHODS" --workers "$THREADS"
run_once "$PLAN_DIR/stage_markers/.stage_complete_high_compact_8taxa_method_policy" babappa aligner-method-policy --align-dir "$WORKSPACE/align_high_compact_8taxa" --site-map-dir "$WORKSPACE/site_map_high_compact_8taxa" --outdir "$WORKSPACE/method_policy_high_compact_8taxa" --max-conflict-fraction 0.03 --max-frame-error-fraction 0.0 --max-method-failure-fraction 0.01
run_once "$PLAN_DIR/stage_markers/.stage_complete_high_compact_8taxa_tensors" babappa build-tensors --sim-dir "$WORKSPACE/sim_high_compact_8taxa" --align-dir "$WORKSPACE/align_high_compact_8taxa" --outdir "$WORKSPACE/tensors_high_compact_8taxa" --methods "$METHODS" --workers "$THREADS"
run_once "$PLAN_DIR/stage_markers/.stage_complete_high_compact_8taxa_index" babappa index-dataset --tensor-dir "$WORKSPACE/tensors_high_compact_8taxa" --outdir "$WORKSPACE/dataset_high_compact_8taxa" --methods "$METHODS" --workers "$THREADS"
run_once "$PLAN_DIR/stage_markers/.stage_complete_high_compact_8taxa_labels" babappa extract-branch-site-labels --dataset-dir "$WORKSPACE/dataset_high_compact_8taxa" --site-map-dir "$WORKSPACE/site_map_high_compact_8taxa" --outdir "$WORKSPACE/labels_high_compact_8taxa" --truth-mode explicit --aligned-site-mode mapped --foreground-source truth --streaming-output
run_once "$PLAN_DIR/stage_markers/.stage_complete_high_compact_8taxa_branch_dataset" babappa build-branch-site-dataset --dataset-dir "$WORKSPACE/dataset_high_compact_8taxa" --branch-site-labels "$WORKSPACE/labels_high_compact_8taxa/branch_site_oracle_labels.tsv" --outdir "$WORKSPACE/branch_dataset_high_compact_8taxa" --negative-downsample-ratio 5 --seed 42 --require-mappable-sites --streaming --max-output-rows 700000
run_once "$PLAN_DIR/stage_markers/.stage_complete_high_compact_8taxa_validate_branch_dataset" babappa validate-branch-site-dataset --branch-site-dataset-dir "$WORKSPACE/branch_dataset_high_compact_8taxa"
cleanup_path "$WORKSPACE/sim_high_compact_8taxa"; cleanup_path "$WORKSPACE/align_high_compact_8taxa"; cleanup_path "$WORKSPACE/site_map_high_compact_8taxa"; cleanup_path "$WORKSPACE/method_policy_high_compact_8taxa"; cleanup_path "$WORKSPACE/tensors_high_compact_8taxa"; cleanup_path "$WORKSPACE/dataset_high_compact_8taxa"; cleanup_path "$WORKSPACE/labels_high_compact_8taxa"

echo "--- chunk high_standard_12taxa: families=5000 taxa=12 codons=420 ---"
run_once "$PLAN_DIR/stage_markers/.stage_complete_high_standard_12taxa_simulate" babappa simulate --outdir "$WORKSPACE/sim_high_standard_12taxa" --n-families 5000 --n-taxa 12 --n-codons 420 --seed 2044 --positive-rate 0.5 --selected-site-fraction 0.05 --mutation-rate 0.05 --saturation-tier high --workers "$THREADS"
run_once "$PLAN_DIR/stage_markers/.stage_complete_high_standard_12taxa_validate_sim" babappa validate-sim --sim-dir "$WORKSPACE/sim_high_standard_12taxa" --require-branch-truth
run_once "$PLAN_DIR/stage_markers/.stage_complete_high_standard_12taxa_align" babappa align-external --sim-dir "$WORKSPACE/sim_high_standard_12taxa" --outdir "$WORKSPACE/align_high_standard_12taxa" --methods "$METHODS" --threads "$THREADS"
run_once "$PLAN_DIR/stage_markers/.stage_complete_high_standard_12taxa_align_methods" require_alignment_methods "$WORKSPACE/align_high_standard_12taxa" "$METHODS"
run_once "$PLAN_DIR/stage_markers/.stage_complete_high_standard_12taxa_site_map" babappa build-site-map --sim-dir "$WORKSPACE/sim_high_standard_12taxa" --align-dir "$WORKSPACE/align_high_standard_12taxa" --outdir "$WORKSPACE/site_map_high_standard_12taxa" --methods "$METHODS" --workers "$THREADS"
run_once "$PLAN_DIR/stage_markers/.stage_complete_high_standard_12taxa_method_policy" babappa aligner-method-policy --align-dir "$WORKSPACE/align_high_standard_12taxa" --site-map-dir "$WORKSPACE/site_map_high_standard_12taxa" --outdir "$WORKSPACE/method_policy_high_standard_12taxa" --max-conflict-fraction 0.03 --max-frame-error-fraction 0.0 --max-method-failure-fraction 0.01
run_once "$PLAN_DIR/stage_markers/.stage_complete_high_standard_12taxa_tensors" babappa build-tensors --sim-dir "$WORKSPACE/sim_high_standard_12taxa" --align-dir "$WORKSPACE/align_high_standard_12taxa" --outdir "$WORKSPACE/tensors_high_standard_12taxa" --methods "$METHODS" --workers "$THREADS"
run_once "$PLAN_DIR/stage_markers/.stage_complete_high_standard_12taxa_index" babappa index-dataset --tensor-dir "$WORKSPACE/tensors_high_standard_12taxa" --outdir "$WORKSPACE/dataset_high_standard_12taxa" --methods "$METHODS" --workers "$THREADS"
run_once "$PLAN_DIR/stage_markers/.stage_complete_high_standard_12taxa_labels" babappa extract-branch-site-labels --dataset-dir "$WORKSPACE/dataset_high_standard_12taxa" --site-map-dir "$WORKSPACE/site_map_high_standard_12taxa" --outdir "$WORKSPACE/labels_high_standard_12taxa" --truth-mode explicit --aligned-site-mode mapped --foreground-source truth --streaming-output
run_once "$PLAN_DIR/stage_markers/.stage_complete_high_standard_12taxa_branch_dataset" babappa build-branch-site-dataset --dataset-dir "$WORKSPACE/dataset_high_standard_12taxa" --branch-site-labels "$WORKSPACE/labels_high_standard_12taxa/branch_site_oracle_labels.tsv" --outdir "$WORKSPACE/branch_dataset_high_standard_12taxa" --negative-downsample-ratio 5 --seed 42 --require-mappable-sites --streaming --max-output-rows 700000
run_once "$PLAN_DIR/stage_markers/.stage_complete_high_standard_12taxa_validate_branch_dataset" babappa validate-branch-site-dataset --branch-site-dataset-dir "$WORKSPACE/branch_dataset_high_standard_12taxa"
cleanup_path "$WORKSPACE/sim_high_standard_12taxa"; cleanup_path "$WORKSPACE/align_high_standard_12taxa"; cleanup_path "$WORKSPACE/site_map_high_standard_12taxa"; cleanup_path "$WORKSPACE/method_policy_high_standard_12taxa"; cleanup_path "$WORKSPACE/tensors_high_standard_12taxa"; cleanup_path "$WORKSPACE/dataset_high_standard_12taxa"; cleanup_path "$WORKSPACE/labels_high_standard_12taxa"

echo "--- chunk high_long_20taxa: families=5000 taxa=20 codons=720 ---"
run_once "$PLAN_DIR/stage_markers/.stage_complete_high_long_20taxa_simulate" babappa simulate --outdir "$WORKSPACE/sim_high_long_20taxa" --n-families 5000 --n-taxa 20 --n-codons 720 --seed 2045 --positive-rate 0.5 --selected-site-fraction 0.04 --mutation-rate 0.055 --saturation-tier high --workers "$THREADS"
run_once "$PLAN_DIR/stage_markers/.stage_complete_high_long_20taxa_validate_sim" babappa validate-sim --sim-dir "$WORKSPACE/sim_high_long_20taxa" --require-branch-truth
run_once "$PLAN_DIR/stage_markers/.stage_complete_high_long_20taxa_align" babappa align-external --sim-dir "$WORKSPACE/sim_high_long_20taxa" --outdir "$WORKSPACE/align_high_long_20taxa" --methods "$METHODS" --threads "$THREADS"
run_once "$PLAN_DIR/stage_markers/.stage_complete_high_long_20taxa_align_methods" require_alignment_methods "$WORKSPACE/align_high_long_20taxa" "$METHODS"
run_once "$PLAN_DIR/stage_markers/.stage_complete_high_long_20taxa_site_map" babappa build-site-map --sim-dir "$WORKSPACE/sim_high_long_20taxa" --align-dir "$WORKSPACE/align_high_long_20taxa" --outdir "$WORKSPACE/site_map_high_long_20taxa" --methods "$METHODS" --workers "$THREADS"
run_once "$PLAN_DIR/stage_markers/.stage_complete_high_long_20taxa_method_policy" babappa aligner-method-policy --align-dir "$WORKSPACE/align_high_long_20taxa" --site-map-dir "$WORKSPACE/site_map_high_long_20taxa" --outdir "$WORKSPACE/method_policy_high_long_20taxa" --max-conflict-fraction 0.03 --max-frame-error-fraction 0.0 --max-method-failure-fraction 0.01
run_once "$PLAN_DIR/stage_markers/.stage_complete_high_long_20taxa_tensors" babappa build-tensors --sim-dir "$WORKSPACE/sim_high_long_20taxa" --align-dir "$WORKSPACE/align_high_long_20taxa" --outdir "$WORKSPACE/tensors_high_long_20taxa" --methods "$METHODS" --workers "$THREADS"
run_once "$PLAN_DIR/stage_markers/.stage_complete_high_long_20taxa_index" babappa index-dataset --tensor-dir "$WORKSPACE/tensors_high_long_20taxa" --outdir "$WORKSPACE/dataset_high_long_20taxa" --methods "$METHODS" --workers "$THREADS"
run_once "$PLAN_DIR/stage_markers/.stage_complete_high_long_20taxa_labels" babappa extract-branch-site-labels --dataset-dir "$WORKSPACE/dataset_high_long_20taxa" --site-map-dir "$WORKSPACE/site_map_high_long_20taxa" --outdir "$WORKSPACE/labels_high_long_20taxa" --truth-mode explicit --aligned-site-mode mapped --foreground-source truth --streaming-output
run_once "$PLAN_DIR/stage_markers/.stage_complete_high_long_20taxa_branch_dataset" babappa build-branch-site-dataset --dataset-dir "$WORKSPACE/dataset_high_long_20taxa" --branch-site-labels "$WORKSPACE/labels_high_long_20taxa/branch_site_oracle_labels.tsv" --outdir "$WORKSPACE/branch_dataset_high_long_20taxa" --negative-downsample-ratio 5 --seed 42 --require-mappable-sites --streaming --max-output-rows 700000
run_once "$PLAN_DIR/stage_markers/.stage_complete_high_long_20taxa_validate_branch_dataset" babappa validate-branch-site-dataset --branch-site-dataset-dir "$WORKSPACE/branch_dataset_high_long_20taxa"
cleanup_path "$WORKSPACE/sim_high_long_20taxa"; cleanup_path "$WORKSPACE/align_high_long_20taxa"; cleanup_path "$WORKSPACE/site_map_high_long_20taxa"; cleanup_path "$WORKSPACE/method_policy_high_long_20taxa"; cleanup_path "$WORKSPACE/tensors_high_long_20taxa"; cleanup_path "$WORKSPACE/dataset_high_long_20taxa"; cleanup_path "$WORKSPACE/labels_high_long_20taxa"

echo "--- chunk high_very_long_32taxa: families=5000 taxa=32 codons=960 ---"
run_once "$PLAN_DIR/stage_markers/.stage_complete_high_very_long_32taxa_simulate" babappa simulate --outdir "$WORKSPACE/sim_high_very_long_32taxa" --n-families 5000 --n-taxa 32 --n-codons 960 --seed 2046 --positive-rate 0.5 --selected-site-fraction 0.03 --mutation-rate 0.06 --saturation-tier high --workers "$THREADS"
run_once "$PLAN_DIR/stage_markers/.stage_complete_high_very_long_32taxa_validate_sim" babappa validate-sim --sim-dir "$WORKSPACE/sim_high_very_long_32taxa" --require-branch-truth
run_once "$PLAN_DIR/stage_markers/.stage_complete_high_very_long_32taxa_align" babappa align-external --sim-dir "$WORKSPACE/sim_high_very_long_32taxa" --outdir "$WORKSPACE/align_high_very_long_32taxa" --methods "$METHODS" --threads "$THREADS"
run_once "$PLAN_DIR/stage_markers/.stage_complete_high_very_long_32taxa_align_methods" require_alignment_methods "$WORKSPACE/align_high_very_long_32taxa" "$METHODS"
run_once "$PLAN_DIR/stage_markers/.stage_complete_high_very_long_32taxa_site_map" babappa build-site-map --sim-dir "$WORKSPACE/sim_high_very_long_32taxa" --align-dir "$WORKSPACE/align_high_very_long_32taxa" --outdir "$WORKSPACE/site_map_high_very_long_32taxa" --methods "$METHODS" --workers "$THREADS"
run_once "$PLAN_DIR/stage_markers/.stage_complete_high_very_long_32taxa_method_policy" babappa aligner-method-policy --align-dir "$WORKSPACE/align_high_very_long_32taxa" --site-map-dir "$WORKSPACE/site_map_high_very_long_32taxa" --outdir "$WORKSPACE/method_policy_high_very_long_32taxa" --max-conflict-fraction 0.03 --max-frame-error-fraction 0.0 --max-method-failure-fraction 0.01
run_once "$PLAN_DIR/stage_markers/.stage_complete_high_very_long_32taxa_tensors" babappa build-tensors --sim-dir "$WORKSPACE/sim_high_very_long_32taxa" --align-dir "$WORKSPACE/align_high_very_long_32taxa" --outdir "$WORKSPACE/tensors_high_very_long_32taxa" --methods "$METHODS" --workers "$THREADS"
run_once "$PLAN_DIR/stage_markers/.stage_complete_high_very_long_32taxa_index" babappa index-dataset --tensor-dir "$WORKSPACE/tensors_high_very_long_32taxa" --outdir "$WORKSPACE/dataset_high_very_long_32taxa" --methods "$METHODS" --workers "$THREADS"
run_once "$PLAN_DIR/stage_markers/.stage_complete_high_very_long_32taxa_labels" babappa extract-branch-site-labels --dataset-dir "$WORKSPACE/dataset_high_very_long_32taxa" --site-map-dir "$WORKSPACE/site_map_high_very_long_32taxa" --outdir "$WORKSPACE/labels_high_very_long_32taxa" --truth-mode explicit --aligned-site-mode mapped --foreground-source truth --streaming-output
run_once "$PLAN_DIR/stage_markers/.stage_complete_high_very_long_32taxa_branch_dataset" babappa build-branch-site-dataset --dataset-dir "$WORKSPACE/dataset_high_very_long_32taxa" --branch-site-labels "$WORKSPACE/labels_high_very_long_32taxa/branch_site_oracle_labels.tsv" --outdir "$WORKSPACE/branch_dataset_high_very_long_32taxa" --negative-downsample-ratio 5 --seed 42 --require-mappable-sites --streaming --max-output-rows 700000
run_once "$PLAN_DIR/stage_markers/.stage_complete_high_very_long_32taxa_validate_branch_dataset" babappa validate-branch-site-dataset --branch-site-dataset-dir "$WORKSPACE/branch_dataset_high_very_long_32taxa"
cleanup_path "$WORKSPACE/sim_high_very_long_32taxa"; cleanup_path "$WORKSPACE/align_high_very_long_32taxa"; cleanup_path "$WORKSPACE/site_map_high_very_long_32taxa"; cleanup_path "$WORKSPACE/method_policy_high_very_long_32taxa"; cleanup_path "$WORKSPACE/tensors_high_very_long_32taxa"; cleanup_path "$WORKSPACE/dataset_high_very_long_32taxa"; cleanup_path "$WORKSPACE/labels_high_very_long_32taxa"

run_once "$PLAN_DIR/stage_markers/.stage_complete_high_merge" babappa merge-branch-site-datasets --dataset-dirs "$WORKSPACE/branch_dataset_high_short_6taxa,$WORKSPACE/branch_dataset_high_compact_8taxa,$WORKSPACE/branch_dataset_high_standard_12taxa,$WORKSPACE/branch_dataset_high_long_20taxa,$WORKSPACE/branch_dataset_high_very_long_32taxa" --outdir "$WORKSPACE/branch_site_dataset_high_merged"
run_once "$PLAN_DIR/stage_markers/.stage_complete_high_train" babappa train-branch-site-neural --branch-site-dataset-dir "$WORKSPACE/branch_site_dataset_high_merged" --outdir "$WORKSPACE/branch_site_neural_high" --device "$DEVICE" --batch-size "$BATCH_SIZE" --threads "$THREADS" --feature-policy "$FEATURE_POLICY" --epochs 10 --learning-rate 0.001 --weight-decay 0.0001 --hidden-dim 64 --dropout 0.1 --positive-class-weight auto --monitor-metric val_auroc --max-train-items 300000 --max-val-items 75000 --max-calib-items 75000 --max-test-items 75000
run_once "$PLAN_DIR/stage_markers/.stage_complete_high_validate_train" babappa validate-branch-site-neural --model-dir "$WORKSPACE/branch_site_neural_high"
run_once "$PLAN_DIR/stage_markers/.stage_complete_high_calibrate" babappa calibrate-branch-site-neural --model-dir "$WORKSPACE/branch_site_neural_high" --outdir "$WORKSPACE/branch_site_calibration_high"
run_once "$PLAN_DIR/stage_markers/.stage_complete_high_validate_calibration" babappa validate-branch-site-calibration --calibration-dir "$WORKSPACE/branch_site_calibration_high"
run_once "$PLAN_DIR/stage_markers/.stage_complete_high_aggregate" babappa aggregate-branch-sites --predictions "$WORKSPACE/branch_site_neural_high/branch_site_neural_predictions.tsv" --outdir "$WORKSPACE/branch_aggregation_high"
run_once "$PLAN_DIR/stage_markers/.stage_complete_high_controls" babappa branch-aggregation-controls --predictions "$WORKSPACE/branch_site_neural_high/branch_site_neural_predictions.tsv" --outdir "$WORKSPACE/branch_aggregation_controls_high" --n-permutations 100 --seed 42 --workers "$THREADS"
run_once "$PLAN_DIR/stage_markers/.stage_complete_high_threshold" babappa branch-site-threshold-policy --predictions "$WORKSPACE/branch_site_calibration_high/branch_site_calibrated_predictions.tsv" --outdir "$WORKSPACE/branch_site_threshold_policy_high" --probability-column prob_positive_raw --calibrated-probability-column prob_positive_calibrated
run_once "$PLAN_DIR/stage_markers/.stage_complete_high_aggregation_policy" babappa branch-aggregation-threshold-policy --aggregation-dir "$WORKSPACE/branch_aggregation_high" --outdir "$WORKSPACE/branch_aggregation_threshold_policy_high"
run_once "$PLAN_DIR/stage_markers/.stage_complete_high_summary" babappa summarize-branch-site-run --outdir "$WORKSPACE/branch_site_run_summary_high" --title "BABAPPA variable-length normalized-v2 high summary" --branch-site-dataset-dir "$WORKSPACE/branch_site_dataset_high_merged" --branch-site-neural-dir "$WORKSPACE/branch_site_neural_high" --branch-site-calibration-dir "$WORKSPACE/branch_site_calibration_high" --branch-aggregation-dir "$WORKSPACE/branch_aggregation_high" --branch-aggregation-controls-dir "$WORKSPACE/branch_aggregation_controls_high" --branch-site-threshold-policy-dir "$WORKSPACE/branch_site_threshold_policy_high" --branch-aggregation-threshold-policy-dir "$WORKSPACE/branch_aggregation_threshold_policy_high"
cleanup_path "$WORKSPACE/branch_site_dataset_high_merged"; for d in "$WORKSPACE/branch_dataset_high_short_6taxa" "$WORKSPACE/branch_dataset_high_compact_8taxa" "$WORKSPACE/branch_dataset_high_standard_12taxa" "$WORKSPACE/branch_dataset_high_long_20taxa" "$WORKSPACE/branch_dataset_high_very_long_32taxa"; do cleanup_path "$d"; done

echo "=== tier extreme ==="
mkdir -p "$WORKSPACE/tier_extreme_datasets"
echo "--- chunk extreme_short_6taxa: families=5000 taxa=6 codons=120 ---"
run_once "$PLAN_DIR/stage_markers/.stage_complete_extreme_short_6taxa_simulate" babappa simulate --outdir "$WORKSPACE/sim_extreme_short_6taxa" --n-families 5000 --n-taxa 6 --n-codons 120 --seed 3042 --positive-rate 0.5 --selected-site-fraction 0.03 --mutation-rate 0.04 --saturation-tier extreme --workers "$THREADS"
run_once "$PLAN_DIR/stage_markers/.stage_complete_extreme_short_6taxa_validate_sim" babappa validate-sim --sim-dir "$WORKSPACE/sim_extreme_short_6taxa" --require-branch-truth
run_once "$PLAN_DIR/stage_markers/.stage_complete_extreme_short_6taxa_align" babappa align-external --sim-dir "$WORKSPACE/sim_extreme_short_6taxa" --outdir "$WORKSPACE/align_extreme_short_6taxa" --methods "$METHODS" --threads "$THREADS"
run_once "$PLAN_DIR/stage_markers/.stage_complete_extreme_short_6taxa_align_methods" require_alignment_methods "$WORKSPACE/align_extreme_short_6taxa" "$METHODS"
run_once "$PLAN_DIR/stage_markers/.stage_complete_extreme_short_6taxa_site_map" babappa build-site-map --sim-dir "$WORKSPACE/sim_extreme_short_6taxa" --align-dir "$WORKSPACE/align_extreme_short_6taxa" --outdir "$WORKSPACE/site_map_extreme_short_6taxa" --methods "$METHODS" --workers "$THREADS"
run_once "$PLAN_DIR/stage_markers/.stage_complete_extreme_short_6taxa_method_policy" babappa aligner-method-policy --align-dir "$WORKSPACE/align_extreme_short_6taxa" --site-map-dir "$WORKSPACE/site_map_extreme_short_6taxa" --outdir "$WORKSPACE/method_policy_extreme_short_6taxa" --max-conflict-fraction 0.03 --max-frame-error-fraction 0.0 --max-method-failure-fraction 0.01
run_once "$PLAN_DIR/stage_markers/.stage_complete_extreme_short_6taxa_tensors" babappa build-tensors --sim-dir "$WORKSPACE/sim_extreme_short_6taxa" --align-dir "$WORKSPACE/align_extreme_short_6taxa" --outdir "$WORKSPACE/tensors_extreme_short_6taxa" --methods "$METHODS" --workers "$THREADS"
run_once "$PLAN_DIR/stage_markers/.stage_complete_extreme_short_6taxa_index" babappa index-dataset --tensor-dir "$WORKSPACE/tensors_extreme_short_6taxa" --outdir "$WORKSPACE/dataset_extreme_short_6taxa" --methods "$METHODS" --workers "$THREADS"
run_once "$PLAN_DIR/stage_markers/.stage_complete_extreme_short_6taxa_labels" babappa extract-branch-site-labels --dataset-dir "$WORKSPACE/dataset_extreme_short_6taxa" --site-map-dir "$WORKSPACE/site_map_extreme_short_6taxa" --outdir "$WORKSPACE/labels_extreme_short_6taxa" --truth-mode explicit --aligned-site-mode mapped --foreground-source truth --streaming-output
run_once "$PLAN_DIR/stage_markers/.stage_complete_extreme_short_6taxa_branch_dataset" babappa build-branch-site-dataset --dataset-dir "$WORKSPACE/dataset_extreme_short_6taxa" --branch-site-labels "$WORKSPACE/labels_extreme_short_6taxa/branch_site_oracle_labels.tsv" --outdir "$WORKSPACE/branch_dataset_extreme_short_6taxa" --negative-downsample-ratio 5 --seed 42 --require-mappable-sites --streaming --max-output-rows 700000
run_once "$PLAN_DIR/stage_markers/.stage_complete_extreme_short_6taxa_validate_branch_dataset" babappa validate-branch-site-dataset --branch-site-dataset-dir "$WORKSPACE/branch_dataset_extreme_short_6taxa"
cleanup_path "$WORKSPACE/sim_extreme_short_6taxa"; cleanup_path "$WORKSPACE/align_extreme_short_6taxa"; cleanup_path "$WORKSPACE/site_map_extreme_short_6taxa"; cleanup_path "$WORKSPACE/method_policy_extreme_short_6taxa"; cleanup_path "$WORKSPACE/tensors_extreme_short_6taxa"; cleanup_path "$WORKSPACE/dataset_extreme_short_6taxa"; cleanup_path "$WORKSPACE/labels_extreme_short_6taxa"

echo "--- chunk extreme_compact_8taxa: families=5000 taxa=8 codons=240 ---"
run_once "$PLAN_DIR/stage_markers/.stage_complete_extreme_compact_8taxa_simulate" babappa simulate --outdir "$WORKSPACE/sim_extreme_compact_8taxa" --n-families 5000 --n-taxa 8 --n-codons 240 --seed 3043 --positive-rate 0.5 --selected-site-fraction 0.04 --mutation-rate 0.045 --saturation-tier extreme --workers "$THREADS"
run_once "$PLAN_DIR/stage_markers/.stage_complete_extreme_compact_8taxa_validate_sim" babappa validate-sim --sim-dir "$WORKSPACE/sim_extreme_compact_8taxa" --require-branch-truth
run_once "$PLAN_DIR/stage_markers/.stage_complete_extreme_compact_8taxa_align" babappa align-external --sim-dir "$WORKSPACE/sim_extreme_compact_8taxa" --outdir "$WORKSPACE/align_extreme_compact_8taxa" --methods "$METHODS" --threads "$THREADS"
run_once "$PLAN_DIR/stage_markers/.stage_complete_extreme_compact_8taxa_align_methods" require_alignment_methods "$WORKSPACE/align_extreme_compact_8taxa" "$METHODS"
run_once "$PLAN_DIR/stage_markers/.stage_complete_extreme_compact_8taxa_site_map" babappa build-site-map --sim-dir "$WORKSPACE/sim_extreme_compact_8taxa" --align-dir "$WORKSPACE/align_extreme_compact_8taxa" --outdir "$WORKSPACE/site_map_extreme_compact_8taxa" --methods "$METHODS" --workers "$THREADS"
run_once "$PLAN_DIR/stage_markers/.stage_complete_extreme_compact_8taxa_method_policy" babappa aligner-method-policy --align-dir "$WORKSPACE/align_extreme_compact_8taxa" --site-map-dir "$WORKSPACE/site_map_extreme_compact_8taxa" --outdir "$WORKSPACE/method_policy_extreme_compact_8taxa" --max-conflict-fraction 0.03 --max-frame-error-fraction 0.0 --max-method-failure-fraction 0.01
run_once "$PLAN_DIR/stage_markers/.stage_complete_extreme_compact_8taxa_tensors" babappa build-tensors --sim-dir "$WORKSPACE/sim_extreme_compact_8taxa" --align-dir "$WORKSPACE/align_extreme_compact_8taxa" --outdir "$WORKSPACE/tensors_extreme_compact_8taxa" --methods "$METHODS" --workers "$THREADS"
run_once "$PLAN_DIR/stage_markers/.stage_complete_extreme_compact_8taxa_index" babappa index-dataset --tensor-dir "$WORKSPACE/tensors_extreme_compact_8taxa" --outdir "$WORKSPACE/dataset_extreme_compact_8taxa" --methods "$METHODS" --workers "$THREADS"
run_once "$PLAN_DIR/stage_markers/.stage_complete_extreme_compact_8taxa_labels" babappa extract-branch-site-labels --dataset-dir "$WORKSPACE/dataset_extreme_compact_8taxa" --site-map-dir "$WORKSPACE/site_map_extreme_compact_8taxa" --outdir "$WORKSPACE/labels_extreme_compact_8taxa" --truth-mode explicit --aligned-site-mode mapped --foreground-source truth --streaming-output
run_once "$PLAN_DIR/stage_markers/.stage_complete_extreme_compact_8taxa_branch_dataset" babappa build-branch-site-dataset --dataset-dir "$WORKSPACE/dataset_extreme_compact_8taxa" --branch-site-labels "$WORKSPACE/labels_extreme_compact_8taxa/branch_site_oracle_labels.tsv" --outdir "$WORKSPACE/branch_dataset_extreme_compact_8taxa" --negative-downsample-ratio 5 --seed 42 --require-mappable-sites --streaming --max-output-rows 700000
run_once "$PLAN_DIR/stage_markers/.stage_complete_extreme_compact_8taxa_validate_branch_dataset" babappa validate-branch-site-dataset --branch-site-dataset-dir "$WORKSPACE/branch_dataset_extreme_compact_8taxa"
cleanup_path "$WORKSPACE/sim_extreme_compact_8taxa"; cleanup_path "$WORKSPACE/align_extreme_compact_8taxa"; cleanup_path "$WORKSPACE/site_map_extreme_compact_8taxa"; cleanup_path "$WORKSPACE/method_policy_extreme_compact_8taxa"; cleanup_path "$WORKSPACE/tensors_extreme_compact_8taxa"; cleanup_path "$WORKSPACE/dataset_extreme_compact_8taxa"; cleanup_path "$WORKSPACE/labels_extreme_compact_8taxa"

echo "--- chunk extreme_standard_12taxa: families=5000 taxa=12 codons=420 ---"
run_once "$PLAN_DIR/stage_markers/.stage_complete_extreme_standard_12taxa_simulate" babappa simulate --outdir "$WORKSPACE/sim_extreme_standard_12taxa" --n-families 5000 --n-taxa 12 --n-codons 420 --seed 3044 --positive-rate 0.5 --selected-site-fraction 0.05 --mutation-rate 0.05 --saturation-tier extreme --workers "$THREADS"
run_once "$PLAN_DIR/stage_markers/.stage_complete_extreme_standard_12taxa_validate_sim" babappa validate-sim --sim-dir "$WORKSPACE/sim_extreme_standard_12taxa" --require-branch-truth
run_once "$PLAN_DIR/stage_markers/.stage_complete_extreme_standard_12taxa_align" babappa align-external --sim-dir "$WORKSPACE/sim_extreme_standard_12taxa" --outdir "$WORKSPACE/align_extreme_standard_12taxa" --methods "$METHODS" --threads "$THREADS"
run_once "$PLAN_DIR/stage_markers/.stage_complete_extreme_standard_12taxa_align_methods" require_alignment_methods "$WORKSPACE/align_extreme_standard_12taxa" "$METHODS"
run_once "$PLAN_DIR/stage_markers/.stage_complete_extreme_standard_12taxa_site_map" babappa build-site-map --sim-dir "$WORKSPACE/sim_extreme_standard_12taxa" --align-dir "$WORKSPACE/align_extreme_standard_12taxa" --outdir "$WORKSPACE/site_map_extreme_standard_12taxa" --methods "$METHODS" --workers "$THREADS"
run_once "$PLAN_DIR/stage_markers/.stage_complete_extreme_standard_12taxa_method_policy" babappa aligner-method-policy --align-dir "$WORKSPACE/align_extreme_standard_12taxa" --site-map-dir "$WORKSPACE/site_map_extreme_standard_12taxa" --outdir "$WORKSPACE/method_policy_extreme_standard_12taxa" --max-conflict-fraction 0.03 --max-frame-error-fraction 0.0 --max-method-failure-fraction 0.01
run_once "$PLAN_DIR/stage_markers/.stage_complete_extreme_standard_12taxa_tensors" babappa build-tensors --sim-dir "$WORKSPACE/sim_extreme_standard_12taxa" --align-dir "$WORKSPACE/align_extreme_standard_12taxa" --outdir "$WORKSPACE/tensors_extreme_standard_12taxa" --methods "$METHODS" --workers "$THREADS"
run_once "$PLAN_DIR/stage_markers/.stage_complete_extreme_standard_12taxa_index" babappa index-dataset --tensor-dir "$WORKSPACE/tensors_extreme_standard_12taxa" --outdir "$WORKSPACE/dataset_extreme_standard_12taxa" --methods "$METHODS" --workers "$THREADS"
run_once "$PLAN_DIR/stage_markers/.stage_complete_extreme_standard_12taxa_labels" babappa extract-branch-site-labels --dataset-dir "$WORKSPACE/dataset_extreme_standard_12taxa" --site-map-dir "$WORKSPACE/site_map_extreme_standard_12taxa" --outdir "$WORKSPACE/labels_extreme_standard_12taxa" --truth-mode explicit --aligned-site-mode mapped --foreground-source truth --streaming-output
run_once "$PLAN_DIR/stage_markers/.stage_complete_extreme_standard_12taxa_branch_dataset" babappa build-branch-site-dataset --dataset-dir "$WORKSPACE/dataset_extreme_standard_12taxa" --branch-site-labels "$WORKSPACE/labels_extreme_standard_12taxa/branch_site_oracle_labels.tsv" --outdir "$WORKSPACE/branch_dataset_extreme_standard_12taxa" --negative-downsample-ratio 5 --seed 42 --require-mappable-sites --streaming --max-output-rows 700000
run_once "$PLAN_DIR/stage_markers/.stage_complete_extreme_standard_12taxa_validate_branch_dataset" babappa validate-branch-site-dataset --branch-site-dataset-dir "$WORKSPACE/branch_dataset_extreme_standard_12taxa"
cleanup_path "$WORKSPACE/sim_extreme_standard_12taxa"; cleanup_path "$WORKSPACE/align_extreme_standard_12taxa"; cleanup_path "$WORKSPACE/site_map_extreme_standard_12taxa"; cleanup_path "$WORKSPACE/method_policy_extreme_standard_12taxa"; cleanup_path "$WORKSPACE/tensors_extreme_standard_12taxa"; cleanup_path "$WORKSPACE/dataset_extreme_standard_12taxa"; cleanup_path "$WORKSPACE/labels_extreme_standard_12taxa"

echo "--- chunk extreme_long_20taxa: families=5000 taxa=20 codons=720 ---"
run_once "$PLAN_DIR/stage_markers/.stage_complete_extreme_long_20taxa_simulate" babappa simulate --outdir "$WORKSPACE/sim_extreme_long_20taxa" --n-families 5000 --n-taxa 20 --n-codons 720 --seed 3045 --positive-rate 0.5 --selected-site-fraction 0.04 --mutation-rate 0.055 --saturation-tier extreme --workers "$THREADS"
run_once "$PLAN_DIR/stage_markers/.stage_complete_extreme_long_20taxa_validate_sim" babappa validate-sim --sim-dir "$WORKSPACE/sim_extreme_long_20taxa" --require-branch-truth
run_once "$PLAN_DIR/stage_markers/.stage_complete_extreme_long_20taxa_align" babappa align-external --sim-dir "$WORKSPACE/sim_extreme_long_20taxa" --outdir "$WORKSPACE/align_extreme_long_20taxa" --methods "$METHODS" --threads "$THREADS"
run_once "$PLAN_DIR/stage_markers/.stage_complete_extreme_long_20taxa_align_methods" require_alignment_methods "$WORKSPACE/align_extreme_long_20taxa" "$METHODS"
run_once "$PLAN_DIR/stage_markers/.stage_complete_extreme_long_20taxa_site_map" babappa build-site-map --sim-dir "$WORKSPACE/sim_extreme_long_20taxa" --align-dir "$WORKSPACE/align_extreme_long_20taxa" --outdir "$WORKSPACE/site_map_extreme_long_20taxa" --methods "$METHODS" --workers "$THREADS"
run_once "$PLAN_DIR/stage_markers/.stage_complete_extreme_long_20taxa_method_policy" babappa aligner-method-policy --align-dir "$WORKSPACE/align_extreme_long_20taxa" --site-map-dir "$WORKSPACE/site_map_extreme_long_20taxa" --outdir "$WORKSPACE/method_policy_extreme_long_20taxa" --max-conflict-fraction 0.03 --max-frame-error-fraction 0.0 --max-method-failure-fraction 0.01
run_once "$PLAN_DIR/stage_markers/.stage_complete_extreme_long_20taxa_tensors" babappa build-tensors --sim-dir "$WORKSPACE/sim_extreme_long_20taxa" --align-dir "$WORKSPACE/align_extreme_long_20taxa" --outdir "$WORKSPACE/tensors_extreme_long_20taxa" --methods "$METHODS" --workers "$THREADS"
run_once "$PLAN_DIR/stage_markers/.stage_complete_extreme_long_20taxa_index" babappa index-dataset --tensor-dir "$WORKSPACE/tensors_extreme_long_20taxa" --outdir "$WORKSPACE/dataset_extreme_long_20taxa" --methods "$METHODS" --workers "$THREADS"
run_once "$PLAN_DIR/stage_markers/.stage_complete_extreme_long_20taxa_labels" babappa extract-branch-site-labels --dataset-dir "$WORKSPACE/dataset_extreme_long_20taxa" --site-map-dir "$WORKSPACE/site_map_extreme_long_20taxa" --outdir "$WORKSPACE/labels_extreme_long_20taxa" --truth-mode explicit --aligned-site-mode mapped --foreground-source truth --streaming-output
run_once "$PLAN_DIR/stage_markers/.stage_complete_extreme_long_20taxa_branch_dataset" babappa build-branch-site-dataset --dataset-dir "$WORKSPACE/dataset_extreme_long_20taxa" --branch-site-labels "$WORKSPACE/labels_extreme_long_20taxa/branch_site_oracle_labels.tsv" --outdir "$WORKSPACE/branch_dataset_extreme_long_20taxa" --negative-downsample-ratio 5 --seed 42 --require-mappable-sites --streaming --max-output-rows 700000
run_once "$PLAN_DIR/stage_markers/.stage_complete_extreme_long_20taxa_validate_branch_dataset" babappa validate-branch-site-dataset --branch-site-dataset-dir "$WORKSPACE/branch_dataset_extreme_long_20taxa"
cleanup_path "$WORKSPACE/sim_extreme_long_20taxa"; cleanup_path "$WORKSPACE/align_extreme_long_20taxa"; cleanup_path "$WORKSPACE/site_map_extreme_long_20taxa"; cleanup_path "$WORKSPACE/method_policy_extreme_long_20taxa"; cleanup_path "$WORKSPACE/tensors_extreme_long_20taxa"; cleanup_path "$WORKSPACE/dataset_extreme_long_20taxa"; cleanup_path "$WORKSPACE/labels_extreme_long_20taxa"

echo "--- chunk extreme_very_long_32taxa: families=5000 taxa=32 codons=960 ---"
run_once "$PLAN_DIR/stage_markers/.stage_complete_extreme_very_long_32taxa_simulate" babappa simulate --outdir "$WORKSPACE/sim_extreme_very_long_32taxa" --n-families 5000 --n-taxa 32 --n-codons 960 --seed 3046 --positive-rate 0.5 --selected-site-fraction 0.03 --mutation-rate 0.06 --saturation-tier extreme --workers "$THREADS"
run_once "$PLAN_DIR/stage_markers/.stage_complete_extreme_very_long_32taxa_validate_sim" babappa validate-sim --sim-dir "$WORKSPACE/sim_extreme_very_long_32taxa" --require-branch-truth
run_once "$PLAN_DIR/stage_markers/.stage_complete_extreme_very_long_32taxa_align" babappa align-external --sim-dir "$WORKSPACE/sim_extreme_very_long_32taxa" --outdir "$WORKSPACE/align_extreme_very_long_32taxa" --methods "$METHODS" --threads "$THREADS"
run_once "$PLAN_DIR/stage_markers/.stage_complete_extreme_very_long_32taxa_align_methods" require_alignment_methods "$WORKSPACE/align_extreme_very_long_32taxa" "$METHODS"
run_once "$PLAN_DIR/stage_markers/.stage_complete_extreme_very_long_32taxa_site_map" babappa build-site-map --sim-dir "$WORKSPACE/sim_extreme_very_long_32taxa" --align-dir "$WORKSPACE/align_extreme_very_long_32taxa" --outdir "$WORKSPACE/site_map_extreme_very_long_32taxa" --methods "$METHODS" --workers "$THREADS"
run_once "$PLAN_DIR/stage_markers/.stage_complete_extreme_very_long_32taxa_method_policy" babappa aligner-method-policy --align-dir "$WORKSPACE/align_extreme_very_long_32taxa" --site-map-dir "$WORKSPACE/site_map_extreme_very_long_32taxa" --outdir "$WORKSPACE/method_policy_extreme_very_long_32taxa" --max-conflict-fraction 0.03 --max-frame-error-fraction 0.0 --max-method-failure-fraction 0.01
run_once "$PLAN_DIR/stage_markers/.stage_complete_extreme_very_long_32taxa_tensors" babappa build-tensors --sim-dir "$WORKSPACE/sim_extreme_very_long_32taxa" --align-dir "$WORKSPACE/align_extreme_very_long_32taxa" --outdir "$WORKSPACE/tensors_extreme_very_long_32taxa" --methods "$METHODS" --workers "$THREADS"
run_once "$PLAN_DIR/stage_markers/.stage_complete_extreme_very_long_32taxa_index" babappa index-dataset --tensor-dir "$WORKSPACE/tensors_extreme_very_long_32taxa" --outdir "$WORKSPACE/dataset_extreme_very_long_32taxa" --methods "$METHODS" --workers "$THREADS"
run_once "$PLAN_DIR/stage_markers/.stage_complete_extreme_very_long_32taxa_labels" babappa extract-branch-site-labels --dataset-dir "$WORKSPACE/dataset_extreme_very_long_32taxa" --site-map-dir "$WORKSPACE/site_map_extreme_very_long_32taxa" --outdir "$WORKSPACE/labels_extreme_very_long_32taxa" --truth-mode explicit --aligned-site-mode mapped --foreground-source truth --streaming-output
run_once "$PLAN_DIR/stage_markers/.stage_complete_extreme_very_long_32taxa_branch_dataset" babappa build-branch-site-dataset --dataset-dir "$WORKSPACE/dataset_extreme_very_long_32taxa" --branch-site-labels "$WORKSPACE/labels_extreme_very_long_32taxa/branch_site_oracle_labels.tsv" --outdir "$WORKSPACE/branch_dataset_extreme_very_long_32taxa" --negative-downsample-ratio 5 --seed 42 --require-mappable-sites --streaming --max-output-rows 700000
run_once "$PLAN_DIR/stage_markers/.stage_complete_extreme_very_long_32taxa_validate_branch_dataset" babappa validate-branch-site-dataset --branch-site-dataset-dir "$WORKSPACE/branch_dataset_extreme_very_long_32taxa"
cleanup_path "$WORKSPACE/sim_extreme_very_long_32taxa"; cleanup_path "$WORKSPACE/align_extreme_very_long_32taxa"; cleanup_path "$WORKSPACE/site_map_extreme_very_long_32taxa"; cleanup_path "$WORKSPACE/method_policy_extreme_very_long_32taxa"; cleanup_path "$WORKSPACE/tensors_extreme_very_long_32taxa"; cleanup_path "$WORKSPACE/dataset_extreme_very_long_32taxa"; cleanup_path "$WORKSPACE/labels_extreme_very_long_32taxa"

run_once "$PLAN_DIR/stage_markers/.stage_complete_extreme_merge" babappa merge-branch-site-datasets --dataset-dirs "$WORKSPACE/branch_dataset_extreme_short_6taxa,$WORKSPACE/branch_dataset_extreme_compact_8taxa,$WORKSPACE/branch_dataset_extreme_standard_12taxa,$WORKSPACE/branch_dataset_extreme_long_20taxa,$WORKSPACE/branch_dataset_extreme_very_long_32taxa" --outdir "$WORKSPACE/branch_site_dataset_extreme_merged"
run_once "$PLAN_DIR/stage_markers/.stage_complete_extreme_train" babappa train-branch-site-neural --branch-site-dataset-dir "$WORKSPACE/branch_site_dataset_extreme_merged" --outdir "$WORKSPACE/branch_site_neural_extreme" --device "$DEVICE" --batch-size "$BATCH_SIZE" --threads "$THREADS" --feature-policy "$FEATURE_POLICY" --epochs 10 --learning-rate 0.001 --weight-decay 0.0001 --hidden-dim 64 --dropout 0.1 --positive-class-weight auto --monitor-metric val_auroc --max-train-items 300000 --max-val-items 75000 --max-calib-items 75000 --max-test-items 75000
run_once "$PLAN_DIR/stage_markers/.stage_complete_extreme_validate_train" babappa validate-branch-site-neural --model-dir "$WORKSPACE/branch_site_neural_extreme"
run_once "$PLAN_DIR/stage_markers/.stage_complete_extreme_calibrate" babappa calibrate-branch-site-neural --model-dir "$WORKSPACE/branch_site_neural_extreme" --outdir "$WORKSPACE/branch_site_calibration_extreme"
run_once "$PLAN_DIR/stage_markers/.stage_complete_extreme_validate_calibration" babappa validate-branch-site-calibration --calibration-dir "$WORKSPACE/branch_site_calibration_extreme"
run_once "$PLAN_DIR/stage_markers/.stage_complete_extreme_aggregate" babappa aggregate-branch-sites --predictions "$WORKSPACE/branch_site_neural_extreme/branch_site_neural_predictions.tsv" --outdir "$WORKSPACE/branch_aggregation_extreme"
run_once "$PLAN_DIR/stage_markers/.stage_complete_extreme_controls" babappa branch-aggregation-controls --predictions "$WORKSPACE/branch_site_neural_extreme/branch_site_neural_predictions.tsv" --outdir "$WORKSPACE/branch_aggregation_controls_extreme" --n-permutations 100 --seed 42 --workers "$THREADS"
run_once "$PLAN_DIR/stage_markers/.stage_complete_extreme_threshold" babappa branch-site-threshold-policy --predictions "$WORKSPACE/branch_site_calibration_extreme/branch_site_calibrated_predictions.tsv" --outdir "$WORKSPACE/branch_site_threshold_policy_extreme" --probability-column prob_positive_raw --calibrated-probability-column prob_positive_calibrated
run_once "$PLAN_DIR/stage_markers/.stage_complete_extreme_aggregation_policy" babappa branch-aggregation-threshold-policy --aggregation-dir "$WORKSPACE/branch_aggregation_extreme" --outdir "$WORKSPACE/branch_aggregation_threshold_policy_extreme"
run_once "$PLAN_DIR/stage_markers/.stage_complete_extreme_summary" babappa summarize-branch-site-run --outdir "$WORKSPACE/branch_site_run_summary_extreme" --title "BABAPPA variable-length normalized-v2 extreme summary" --branch-site-dataset-dir "$WORKSPACE/branch_site_dataset_extreme_merged" --branch-site-neural-dir "$WORKSPACE/branch_site_neural_extreme" --branch-site-calibration-dir "$WORKSPACE/branch_site_calibration_extreme" --branch-aggregation-dir "$WORKSPACE/branch_aggregation_extreme" --branch-aggregation-controls-dir "$WORKSPACE/branch_aggregation_controls_extreme" --branch-site-threshold-policy-dir "$WORKSPACE/branch_site_threshold_policy_extreme" --branch-aggregation-threshold-policy-dir "$WORKSPACE/branch_aggregation_threshold_policy_extreme"
cleanup_path "$WORKSPACE/branch_site_dataset_extreme_merged"; for d in "$WORKSPACE/branch_dataset_extreme_short_6taxa" "$WORKSPACE/branch_dataset_extreme_compact_8taxa" "$WORKSPACE/branch_dataset_extreme_standard_12taxa" "$WORKSPACE/branch_dataset_extreme_long_20taxa" "$WORKSPACE/branch_dataset_extreme_very_long_32taxa"; do cleanup_path "$d"; done

mkdir -p "$WORKSPACE/truth_audit"
cat > "$WORKSPACE/truth_audit/branch_truth_status_audit.tsv" <<'EOF'
tier	explicit_branch_site_truth_available	proxy_from_foreground_taxon
low	True	False
moderate	True	False
high	True	False
extreme	True	False
EOF
cat > "$WORKSPACE/truth_audit/branch_truth_status_audit.json" <<'EOF'
{
  "status": "ok",
  "explicit_truth_available": true,
  "proxy_label_tiers": []
}
EOF
cat > "$WORKSPACE/variable_length_100k_validation_report.json" <<'EOF'
{
  "run_identity": {
    "run_name": "variable_length_normalized_v2_100k_mps",
    "feature_policy": "conservative_branch_site_normalized_v2",
    "truth_mode": "explicit",
    "methods": [
      "identity",
      "mafft",
      "babappalign",
      "muscle"
    ]
  },
  "decision": {
    "status": "PENDING_REVIEW",
    "reason": "Long-run script generated retained model/calibration artifacts; inspect tier summaries before release."
  },
  "neural_rows": [],
  "branch_aggregation_rows": [],
  "gene_aggregation_rows": [],
  "controls_rows": []
}
EOF
echo "Variable-length retraining stages completed. Run package_variable_length_deployable.sh after reviewing validation summaries."
