#!/usr/bin/env bash
set -euo pipefail
echo 'USER-RUN ONLY - packages retained model artifacts; does not train.'
if python - <<'PY'
import json
from pathlib import Path
m=json.loads(Path('deployable_model_manifest_template.json').read_text())
raise SystemExit(1 if m.get('blocked') else 0)
PY
then
  mkdir -p package/models package/calibration package/reports
else
  echo 'Package plan is blocked; inspect deployable_model_manifest_template.json.'
  exit 1
fi
cp branch_site_neural_explicit_branch_truth_100k_mps_low_streamed/branch_site_neural_checkpoint.pt package/models/low_branch_site_neural_checkpoint.pt
cp branch_site_neural_explicit_branch_truth_100k_mps_low_streamed/branch_site_neural_model_meta.json package/models/low_branch_site_neural_model_meta.json
cp branch_site_calibration_explicit_branch_truth_100k_mps_low_streamed/branch_site_calibration.json package/calibration/low_branch_site_calibration.json
cp branch_site_calibration_explicit_branch_truth_100k_mps_low_streamed/branch_site_calibrated_metrics.json package/calibration/low_branch_site_calibrated_metrics.json
cp branch_site_neural_explicit_branch_truth_100k_mps_moderate_streamed/branch_site_neural_checkpoint.pt package/models/moderate_branch_site_neural_checkpoint.pt
cp branch_site_neural_explicit_branch_truth_100k_mps_moderate_streamed/branch_site_neural_model_meta.json package/models/moderate_branch_site_neural_model_meta.json
cp branch_site_calibration_explicit_branch_truth_100k_mps_moderate_streamed/branch_site_calibration.json package/calibration/moderate_branch_site_calibration.json
cp branch_site_calibration_explicit_branch_truth_100k_mps_moderate_streamed/branch_site_calibrated_metrics.json package/calibration/moderate_branch_site_calibrated_metrics.json
cp branch_site_neural_explicit_branch_truth_100k_mps_high_streamed/branch_site_neural_checkpoint.pt package/models/high_branch_site_neural_checkpoint.pt
cp branch_site_neural_explicit_branch_truth_100k_mps_high_streamed/branch_site_neural_model_meta.json package/models/high_branch_site_neural_model_meta.json
cp branch_site_calibration_explicit_branch_truth_100k_mps_high_streamed/branch_site_calibration.json package/calibration/high_branch_site_calibration.json
cp branch_site_calibration_explicit_branch_truth_100k_mps_high_streamed/branch_site_calibrated_metrics.json package/calibration/high_branch_site_calibrated_metrics.json
cp branch_site_neural_explicit_branch_truth_100k_mps_extreme_streamed/branch_site_neural_checkpoint.pt package/models/extreme_branch_site_neural_checkpoint.pt
cp branch_site_neural_explicit_branch_truth_100k_mps_extreme_streamed/branch_site_neural_model_meta.json package/models/extreme_branch_site_neural_model_meta.json
cp branch_site_calibration_explicit_branch_truth_100k_mps_extreme_streamed/branch_site_calibration.json package/calibration/extreme_branch_site_calibration.json
cp branch_site_calibration_explicit_branch_truth_100k_mps_extreme_streamed/branch_site_calibrated_metrics.json package/calibration/extreme_branch_site_calibrated_metrics.json
cp deployable_model_manifest_template.json package/deployable_model_manifest.json
cp model_card_template.md package/model_card.md
echo 'Package staged under package/'
